// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/osasadev-lab/aibo_pj/server/ent/dmattachment"
	"github.com/osasadev-lab/aibo_pj/server/ent/dmmessage"
	"github.com/osasadev-lab/aibo_pj/server/ent/user"
)

// DMAttachment is the model entity for the DMAttachment schema.
type DMAttachment struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DmMessageID holds the value of the "dm_message_id" field.
	DmMessageID uuid.UUID `json:"dm_message_id,omitempty"`
	// UploadedBy holds the value of the "uploaded_by" field.
	UploadedBy uuid.UUID `json:"uploaded_by,omitempty"`
	// FileName holds the value of the "file_name" field.
	FileName string `json:"file_name,omitempty"`
	// StorageKey holds the value of the "storage_key" field.
	StorageKey string `json:"storage_key,omitempty"`
	// SizeBytes holds the value of the "size_bytes" field.
	SizeBytes int64 `json:"size_bytes,omitempty"`
	// ContentType holds the value of the "content_type" field.
	ContentType string `json:"content_type,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DMAttachmentQuery when eager-loading is set.
	Edges        DMAttachmentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DMAttachmentEdges holds the relations/edges for other nodes in the graph.
type DMAttachmentEdges struct {
	// Message holds the value of the message edge.
	Message *DMMessage `json:"message,omitempty"`
	// Uploader holds the value of the uploader edge.
	Uploader *User `json:"uploader,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// MessageOrErr returns the Message value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DMAttachmentEdges) MessageOrErr() (*DMMessage, error) {
	if e.Message != nil {
		return e.Message, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: dmmessage.Label}
	}
	return nil, &NotLoadedError{edge: "message"}
}

// UploaderOrErr returns the Uploader value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DMAttachmentEdges) UploaderOrErr() (*User, error) {
	if e.Uploader != nil {
		return e.Uploader, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "uploader"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DMAttachment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dmattachment.FieldSizeBytes:
			values[i] = new(sql.NullInt64)
		case dmattachment.FieldFileName, dmattachment.FieldStorageKey, dmattachment.FieldContentType:
			values[i] = new(sql.NullString)
		case dmattachment.FieldCreatedAt, dmattachment.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case dmattachment.FieldID, dmattachment.FieldDmMessageID, dmattachment.FieldUploadedBy:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DMAttachment fields.
func (_m *DMAttachment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dmattachment.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case dmattachment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case dmattachment.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case dmattachment.FieldDmMessageID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field dm_message_id", values[i])
			} else if value != nil {
				_m.DmMessageID = *value
			}
		case dmattachment.FieldUploadedBy:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field uploaded_by", values[i])
			} else if value != nil {
				_m.UploadedBy = *value
			}
		case dmattachment.FieldFileName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_name", values[i])
			} else if value.Valid {
				_m.FileName = value.String
			}
		case dmattachment.FieldStorageKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field storage_key", values[i])
			} else if value.Valid {
				_m.StorageKey = value.String
			}
		case dmattachment.FieldSizeBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size_bytes", values[i])
			} else if value.Valid {
				_m.SizeBytes = value.Int64
			}
		case dmattachment.FieldContentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_type", values[i])
			} else if value.Valid {
				_m.ContentType = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DMAttachment.
// This includes values selected through modifiers, order, etc.
func (_m *DMAttachment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMessage queries the "message" edge of the DMAttachment entity.
func (_m *DMAttachment) QueryMessage() *DMMessageQuery {
	return NewDMAttachmentClient(_m.config).QueryMessage(_m)
}

// QueryUploader queries the "uploader" edge of the DMAttachment entity.
func (_m *DMAttachment) QueryUploader() *UserQuery {
	return NewDMAttachmentClient(_m.config).QueryUploader(_m)
}

// Update returns a builder for updating this DMAttachment.
// Note that you need to call DMAttachment.Unwrap() before calling this method if this DMAttachment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DMAttachment) Update() *DMAttachmentUpdateOne {
	return NewDMAttachmentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DMAttachment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DMAttachment) Unwrap() *DMAttachment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DMAttachment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DMAttachment) String() string {
	var builder strings.Builder
	builder.WriteString("DMAttachment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("dm_message_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DmMessageID))
	builder.WriteString(", ")
	builder.WriteString("uploaded_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.UploadedBy))
	builder.WriteString(", ")
	builder.WriteString("file_name=")
	builder.WriteString(_m.FileName)
	builder.WriteString(", ")
	builder.WriteString("storage_key=")
	builder.WriteString(_m.StorageKey)
	builder.WriteString(", ")
	builder.WriteString("size_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.SizeBytes))
	builder.WriteString(", ")
	builder.WriteString("content_type=")
	builder.WriteString(_m.ContentType)
	builder.WriteByte(')')
	return builder.String()
}

// DMAttachments is a parsable slice of DMAttachment.
type DMAttachments []*DMAttachment
