// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/osasadev-lab/aibo_pj/server/ent/dmchannel"
	"github.com/osasadev-lab/aibo_pj/server/ent/dmchannelmember"
	"github.com/osasadev-lab/aibo_pj/server/ent/predicate"
	"github.com/osasadev-lab/aibo_pj/server/ent/user"
)

// DMChannelMemberUpdate is the builder for updating DMChannelMember entities.
type DMChannelMemberUpdate struct {
	config
	hooks    []Hook
	mutation *DMChannelMemberMutation
}

// Where appends a list predicates to the DMChannelMemberUpdate builder.
func (_u *DMChannelMemberUpdate) Where(ps ...predicate.DMChannelMember) *DMChannelMemberUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DMChannelMemberUpdate) SetUpdatedAt(v time.Time) *DMChannelMemberUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *DMChannelMemberUpdate) SetChannelID(v uuid.UUID) *DMChannelMemberUpdate {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *DMChannelMemberUpdate) SetNillableChannelID(v *uuid.UUID) *DMChannelMemberUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DMChannelMemberUpdate) SetUserID(v uuid.UUID) *DMChannelMemberUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DMChannelMemberUpdate) SetNillableUserID(v *uuid.UUID) *DMChannelMemberUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetLastReadAt sets the "last_read_at" field.
func (_u *DMChannelMemberUpdate) SetLastReadAt(v time.Time) *DMChannelMemberUpdate {
	_u.mutation.SetLastReadAt(v)
	return _u
}

// SetNillableLastReadAt sets the "last_read_at" field if the given value is not nil.
func (_u *DMChannelMemberUpdate) SetNillableLastReadAt(v *time.Time) *DMChannelMemberUpdate {
	if v != nil {
		_u.SetLastReadAt(*v)
	}
	return _u
}

// ClearLastReadAt clears the value of the "last_read_at" field.
func (_u *DMChannelMemberUpdate) ClearLastReadAt() *DMChannelMemberUpdate {
	_u.mutation.ClearLastReadAt()
	return _u
}

// SetChannel sets the "channel" edge to the DMChannel entity.
func (_u *DMChannelMemberUpdate) SetChannel(v *DMChannel) *DMChannelMemberUpdate {
	return _u.SetChannelID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *DMChannelMemberUpdate) SetUser(v *User) *DMChannelMemberUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the DMChannelMemberMutation object of the builder.
func (_u *DMChannelMemberUpdate) Mutation() *DMChannelMemberMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the DMChannel entity.
func (_u *DMChannelMemberUpdate) ClearChannel() *DMChannelMemberUpdate {
	_u.mutation.ClearChannel()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *DMChannelMemberUpdate) ClearUser() *DMChannelMemberUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DMChannelMemberUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DMChannelMemberUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DMChannelMemberUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DMChannelMemberUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DMChannelMemberUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dmchannelmember.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DMChannelMemberUpdate) check() error {
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DMChannelMember.channel"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DMChannelMember.user"`)
	}
	return nil
}

func (_u *DMChannelMemberUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dmchannelmember.Table, dmchannelmember.Columns, sqlgraph.NewFieldSpec(dmchannelmember.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dmchannelmember.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastReadAt(); ok {
		_spec.SetField(dmchannelmember.FieldLastReadAt, field.TypeTime, value)
	}
	if _u.mutation.LastReadAtCleared() {
		_spec.ClearField(dmchannelmember.FieldLastReadAt, field.TypeTime)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   dmchannelmember.ChannelTable,
			Columns: []string{dmchannelmember.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dmchannel.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   dmchannelmember.ChannelTable,
			Columns: []string{dmchannelmember.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dmchannel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   dmchannelmember.UserTable,
			Columns: []string{dmchannelmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   dmchannelmember.UserTable,
			Columns: []string{dmchannelmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dmchannelmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DMChannelMemberUpdateOne is the builder for updating a single DMChannelMember entity.
type DMChannelMemberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DMChannelMemberMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DMChannelMemberUpdateOne) SetUpdatedAt(v time.Time) *DMChannelMemberUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *DMChannelMemberUpdateOne) SetChannelID(v uuid.UUID) *DMChannelMemberUpdateOne {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *DMChannelMemberUpdateOne) SetNillableChannelID(v *uuid.UUID) *DMChannelMemberUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DMChannelMemberUpdateOne) SetUserID(v uuid.UUID) *DMChannelMemberUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DMChannelMemberUpdateOne) SetNillableUserID(v *uuid.UUID) *DMChannelMemberUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetLastReadAt sets the "last_read_at" field.
func (_u *DMChannelMemberUpdateOne) SetLastReadAt(v time.Time) *DMChannelMemberUpdateOne {
	_u.mutation.SetLastReadAt(v)
	return _u
}

// SetNillableLastReadAt sets the "last_read_at" field if the given value is not nil.
func (_u *DMChannelMemberUpdateOne) SetNillableLastReadAt(v *time.Time) *DMChannelMemberUpdateOne {
	if v != nil {
		_u.SetLastReadAt(*v)
	}
	return _u
}

// ClearLastReadAt clears the value of the "last_read_at" field.
func (_u *DMChannelMemberUpdateOne) ClearLastReadAt() *DMChannelMemberUpdateOne {
	_u.mutation.ClearLastReadAt()
	return _u
}

// SetChannel sets the "channel" edge to the DMChannel entity.
func (_u *DMChannelMemberUpdateOne) SetChannel(v *DMChannel) *DMChannelMemberUpdateOne {
	return _u.SetChannelID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *DMChannelMemberUpdateOne) SetUser(v *User) *DMChannelMemberUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the DMChannelMemberMutation object of the builder.
func (_u *DMChannelMemberUpdateOne) Mutation() *DMChannelMemberMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the DMChannel entity.
func (_u *DMChannelMemberUpdateOne) ClearChannel() *DMChannelMemberUpdateOne {
	_u.mutation.ClearChannel()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *DMChannelMemberUpdateOne) ClearUser() *DMChannelMemberUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the DMChannelMemberUpdate builder.
func (_u *DMChannelMemberUpdateOne) Where(ps ...predicate.DMChannelMember) *DMChannelMemberUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DMChannelMemberUpdateOne) Select(field string, fields ...string) *DMChannelMemberUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DMChannelMember entity.
func (_u *DMChannelMemberUpdateOne) Save(ctx context.Context) (*DMChannelMember, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DMChannelMemberUpdateOne) SaveX(ctx context.Context) *DMChannelMember {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DMChannelMemberUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DMChannelMemberUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DMChannelMemberUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dmchannelmember.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DMChannelMemberUpdateOne) check() error {
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DMChannelMember.channel"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DMChannelMember.user"`)
	}
	return nil
}

func (_u *DMChannelMemberUpdateOne) sqlSave(ctx context.Context) (_node *DMChannelMember, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dmchannelmember.Table, dmchannelmember.Columns, sqlgraph.NewFieldSpec(dmchannelmember.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DMChannelMember.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dmchannelmember.FieldID)
		for _, f := range fields {
			if !dmchannelmember.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dmchannelmember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dmchannelmember.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastReadAt(); ok {
		_spec.SetField(dmchannelmember.FieldLastReadAt, field.TypeTime, value)
	}
	if _u.mutation.LastReadAtCleared() {
		_spec.ClearField(dmchannelmember.FieldLastReadAt, field.TypeTime)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   dmchannelmember.ChannelTable,
			Columns: []string{dmchannelmember.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dmchannel.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   dmchannelmember.ChannelTable,
			Columns: []string{dmchannelmember.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dmchannel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   dmchannelmember.UserTable,
			Columns: []string{dmchannelmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   dmchannelmember.UserTable,
			Columns: []string{dmchannelmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DMChannelMember{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dmchannelmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
