// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/osasadev-lab/aibo_pj/server/ent/dmchannel"
	"github.com/osasadev-lab/aibo_pj/server/ent/dmchannelmember"
	"github.com/osasadev-lab/aibo_pj/server/ent/user"
)

// DMChannelMember is the model entity for the DMChannelMember schema.
type DMChannelMember struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ChannelID holds the value of the "channel_id" field.
	ChannelID uuid.UUID `json:"channel_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// LastReadAt holds the value of the "last_read_at" field.
	LastReadAt *time.Time `json:"last_read_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DMChannelMemberQuery when eager-loading is set.
	Edges        DMChannelMemberEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DMChannelMemberEdges holds the relations/edges for other nodes in the graph.
type DMChannelMemberEdges struct {
	// Channel holds the value of the channel edge.
	Channel *DMChannel `json:"channel,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ChannelOrErr returns the Channel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DMChannelMemberEdges) ChannelOrErr() (*DMChannel, error) {
	if e.Channel != nil {
		return e.Channel, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: dmchannel.Label}
	}
	return nil, &NotLoadedError{edge: "channel"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DMChannelMemberEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DMChannelMember) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dmchannelmember.FieldCreatedAt, dmchannelmember.FieldUpdatedAt, dmchannelmember.FieldLastReadAt:
			values[i] = new(sql.NullTime)
		case dmchannelmember.FieldID, dmchannelmember.FieldChannelID, dmchannelmember.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DMChannelMember fields.
func (_m *DMChannelMember) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dmchannelmember.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case dmchannelmember.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case dmchannelmember.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case dmchannelmember.FieldChannelID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value != nil {
				_m.ChannelID = *value
			}
		case dmchannelmember.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case dmchannelmember.FieldLastReadAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_read_at", values[i])
			} else if value.Valid {
				_m.LastReadAt = new(time.Time)
				*_m.LastReadAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DMChannelMember.
// This includes values selected through modifiers, order, etc.
func (_m *DMChannelMember) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChannel queries the "channel" edge of the DMChannelMember entity.
func (_m *DMChannelMember) QueryChannel() *DMChannelQuery {
	return NewDMChannelMemberClient(_m.config).QueryChannel(_m)
}

// QueryUser queries the "user" edge of the DMChannelMember entity.
func (_m *DMChannelMember) QueryUser() *UserQuery {
	return NewDMChannelMemberClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this DMChannelMember.
// Note that you need to call DMChannelMember.Unwrap() before calling this method if this DMChannelMember
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DMChannelMember) Update() *DMChannelMemberUpdateOne {
	return NewDMChannelMemberClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DMChannelMember entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DMChannelMember) Unwrap() *DMChannelMember {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DMChannelMember is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DMChannelMember) String() string {
	var builder strings.Builder
	builder.WriteString("DMChannelMember(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("channel_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChannelID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	if v := _m.LastReadAt; v != nil {
		builder.WriteString("last_read_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// DMChannelMembers is a parsable slice of DMChannelMember.
type DMChannelMembers []*DMChannelMember
