// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/osasadev-lab/aibo_pj/server/ent/feedback"
	"github.com/osasadev-lab/aibo_pj/server/ent/user"
)

// FeedbackCreate is the builder for creating a Feedback entity.
type FeedbackCreate struct {
	config
	mutation *FeedbackMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *FeedbackCreate) SetCreatedAt(v time.Time) *FeedbackCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FeedbackCreate) SetNillableCreatedAt(v *time.Time) *FeedbackCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *FeedbackCreate) SetUpdatedAt(v time.Time) *FeedbackCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *FeedbackCreate) SetNillableUpdatedAt(v *time.Time) *FeedbackCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *FeedbackCreate) SetUserID(v uuid.UUID) *FeedbackCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetWorkspaceID sets the "workspace_id" field.
func (_c *FeedbackCreate) SetWorkspaceID(v uuid.UUID) *FeedbackCreate {
	_c.mutation.SetWorkspaceID(v)
	return _c
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_c *FeedbackCreate) SetNillableWorkspaceID(v *uuid.UUID) *FeedbackCreate {
	if v != nil {
		_c.SetWorkspaceID(*v)
	}
	return _c
}

// SetBody sets the "body" field.
func (_c *FeedbackCreate) SetBody(v string) *FeedbackCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetPagePath sets the "page_path" field.
func (_c *FeedbackCreate) SetPagePath(v string) *FeedbackCreate {
	_c.mutation.SetPagePath(v)
	return _c
}

// SetNillablePagePath sets the "page_path" field if the given value is not nil.
func (_c *FeedbackCreate) SetNillablePagePath(v *string) *FeedbackCreate {
	if v != nil {
		_c.SetPagePath(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *FeedbackCreate) SetID(v uuid.UUID) *FeedbackCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *FeedbackCreate) SetNillableID(v *uuid.UUID) *FeedbackCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *FeedbackCreate) SetUser(v *User) *FeedbackCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the FeedbackMutation object of the builder.
func (_c *FeedbackCreate) Mutation() *FeedbackMutation {
	return _c.mutation
}

// Save creates the Feedback in the database.
func (_c *FeedbackCreate) Save(ctx context.Context) (*Feedback, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FeedbackCreate) SaveX(ctx context.Context) *Feedback {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FeedbackCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FeedbackCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FeedbackCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := feedback.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := feedback.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := feedback.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FeedbackCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Feedback.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Feedback.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Feedback.user_id"`)}
	}
	if _, ok := _c.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New(`ent: missing required field "Feedback.body"`)}
	}
	if v, ok := _c.mutation.Body(); ok {
		if err := feedback.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "Feedback.body": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Feedback.user"`)}
	}
	return nil
}

func (_c *FeedbackCreate) sqlSave(ctx context.Context) (*Feedback, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FeedbackCreate) createSpec() (*Feedback, *sqlgraph.CreateSpec) {
	var (
		_node = &Feedback{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(feedback.Table, sqlgraph.NewFieldSpec(feedback.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(feedback.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(feedback.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.WorkspaceID(); ok {
		_spec.SetField(feedback.FieldWorkspaceID, field.TypeUUID, value)
		_node.WorkspaceID = &value
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(feedback.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.PagePath(); ok {
		_spec.SetField(feedback.FieldPagePath, field.TypeString, value)
		_node.PagePath = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   feedback.UserTable,
			Columns: []string{feedback.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FeedbackCreateBulk is the builder for creating many Feedback entities in bulk.
type FeedbackCreateBulk struct {
	config
	err      error
	builders []*FeedbackCreate
}

// Save creates the Feedback entities in the database.
func (_c *FeedbackCreateBulk) Save(ctx context.Context) ([]*Feedback, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Feedback, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FeedbackMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FeedbackCreateBulk) SaveX(ctx context.Context) []*Feedback {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FeedbackCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FeedbackCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
