// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/osasadev-lab/aibo_pj/server/ent/feedback"
	"github.com/osasadev-lab/aibo_pj/server/ent/predicate"
)

// FeedbackDelete is the builder for deleting a Feedback entity.
type FeedbackDelete struct {
	config
	hooks    []Hook
	mutation *FeedbackMutation
}

// Where appends a list predicates to the FeedbackDelete builder.
func (_d *FeedbackDelete) Where(ps ...predicate.Feedback) *FeedbackDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *FeedbackDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FeedbackDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *FeedbackDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(feedback.Table, sqlgraph.NewFieldSpec(feedback.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// FeedbackDeleteOne is the builder for deleting a single Feedback entity.
type FeedbackDeleteOne struct {
	_d *FeedbackDelete
}

// Where appends a list predicates to the FeedbackDelete builder.
func (_d *FeedbackDeleteOne) Where(ps ...predicate.Feedback) *FeedbackDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *FeedbackDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{feedback.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FeedbackDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
