// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/osasadev-lab/aibo_pj/server/ent/project"
	"github.com/osasadev-lab/aibo_pj/server/ent/projectstatuscolumn"
)

// ProjectStatusColumn is the model entity for the ProjectStatusColumn schema.
type ProjectStatusColumn struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID uuid.UUID `json:"project_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Position holds the value of the "position" field.
	Position int `json:"position,omitempty"`
	// MapsToStatus holds the value of the "maps_to_status" field.
	MapsToStatus projectstatuscolumn.MapsToStatus `json:"maps_to_status,omitempty"`
	// IsDefault holds the value of the "is_default" field.
	IsDefault bool `json:"is_default,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProjectStatusColumnQuery when eager-loading is set.
	Edges        ProjectStatusColumnEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProjectStatusColumnEdges holds the relations/edges for other nodes in the graph.
type ProjectStatusColumnEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Tasks holds the value of the tasks edge.
	Tasks []*Task `json:"tasks,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProjectStatusColumnEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// TasksOrErr returns the Tasks value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectStatusColumnEdges) TasksOrErr() ([]*Task, error) {
	if e.loadedTypes[1] {
		return e.Tasks, nil
	}
	return nil, &NotLoadedError{edge: "tasks"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProjectStatusColumn) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case projectstatuscolumn.FieldIsDefault:
			values[i] = new(sql.NullBool)
		case projectstatuscolumn.FieldPosition:
			values[i] = new(sql.NullInt64)
		case projectstatuscolumn.FieldName, projectstatuscolumn.FieldMapsToStatus:
			values[i] = new(sql.NullString)
		case projectstatuscolumn.FieldCreatedAt, projectstatuscolumn.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case projectstatuscolumn.FieldID, projectstatuscolumn.FieldProjectID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProjectStatusColumn fields.
func (_m *ProjectStatusColumn) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case projectstatuscolumn.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case projectstatuscolumn.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case projectstatuscolumn.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case projectstatuscolumn.FieldProjectID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value != nil {
				_m.ProjectID = *value
			}
		case projectstatuscolumn.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case projectstatuscolumn.FieldPosition:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field position", values[i])
			} else if value.Valid {
				_m.Position = int(value.Int64)
			}
		case projectstatuscolumn.FieldMapsToStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field maps_to_status", values[i])
			} else if value.Valid {
				_m.MapsToStatus = projectstatuscolumn.MapsToStatus(value.String)
			}
		case projectstatuscolumn.FieldIsDefault:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_default", values[i])
			} else if value.Valid {
				_m.IsDefault = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProjectStatusColumn.
// This includes values selected through modifiers, order, etc.
func (_m *ProjectStatusColumn) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the ProjectStatusColumn entity.
func (_m *ProjectStatusColumn) QueryProject() *ProjectQuery {
	return NewProjectStatusColumnClient(_m.config).QueryProject(_m)
}

// QueryTasks queries the "tasks" edge of the ProjectStatusColumn entity.
func (_m *ProjectStatusColumn) QueryTasks() *TaskQuery {
	return NewProjectStatusColumnClient(_m.config).QueryTasks(_m)
}

// Update returns a builder for updating this ProjectStatusColumn.
// Note that you need to call ProjectStatusColumn.Unwrap() before calling this method if this ProjectStatusColumn
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProjectStatusColumn) Update() *ProjectStatusColumnUpdateOne {
	return NewProjectStatusColumnClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProjectStatusColumn entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProjectStatusColumn) Unwrap() *ProjectStatusColumn {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProjectStatusColumn is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProjectStatusColumn) String() string {
	var builder strings.Builder
	builder.WriteString("ProjectStatusColumn(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("position=")
	builder.WriteString(fmt.Sprintf("%v", _m.Position))
	builder.WriteString(", ")
	builder.WriteString("maps_to_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.MapsToStatus))
	builder.WriteString(", ")
	builder.WriteString("is_default=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDefault))
	builder.WriteByte(')')
	return builder.String()
}

// ProjectStatusColumns is a parsable slice of ProjectStatusColumn.
type ProjectStatusColumns []*ProjectStatusColumn
