// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/osasadev-lab/aibo_pj/server/ent/remindersend"
	"github.com/osasadev-lab/aibo_pj/server/ent/user"
)

// ReminderSend is the model entity for the ReminderSend schema.
type ReminderSend struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// Type holds the value of the "type" field.
	Type remindersend.Type `json:"type,omitempty"`
	// SentDate holds the value of the "sent_date" field.
	SentDate time.Time `json:"sent_date,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReminderSendQuery when eager-loading is set.
	Edges        ReminderSendEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ReminderSendEdges holds the relations/edges for other nodes in the graph.
type ReminderSendEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReminderSendEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReminderSend) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case remindersend.FieldType:
			values[i] = new(sql.NullString)
		case remindersend.FieldCreatedAt, remindersend.FieldUpdatedAt, remindersend.FieldSentDate:
			values[i] = new(sql.NullTime)
		case remindersend.FieldID, remindersend.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReminderSend fields.
func (_m *ReminderSend) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case remindersend.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case remindersend.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case remindersend.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case remindersend.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case remindersend.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = remindersend.Type(value.String)
			}
		case remindersend.FieldSentDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field sent_date", values[i])
			} else if value.Valid {
				_m.SentDate = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReminderSend.
// This includes values selected through modifiers, order, etc.
func (_m *ReminderSend) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the ReminderSend entity.
func (_m *ReminderSend) QueryUser() *UserQuery {
	return NewReminderSendClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this ReminderSend.
// Note that you need to call ReminderSend.Unwrap() before calling this method if this ReminderSend
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ReminderSend) Update() *ReminderSendUpdateOne {
	return NewReminderSendClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ReminderSend entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ReminderSend) Unwrap() *ReminderSend {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReminderSend is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ReminderSend) String() string {
	var builder strings.Builder
	builder.WriteString("ReminderSend(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("sent_date=")
	builder.WriteString(_m.SentDate.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ReminderSends is a parsable slice of ReminderSend.
type ReminderSends []*ReminderSend
