// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/osasadev-lab/aibo_pj/server/ent/task"
	"github.com/osasadev-lab/aibo_pj/server/ent/taskcalendarevent"
	"github.com/osasadev-lab/aibo_pj/server/ent/user"
)

// TaskCalendarEvent is the model entity for the TaskCalendarEvent schema.
type TaskCalendarEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID uuid.UUID `json:"task_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// GoogleEventID holds the value of the "google_event_id" field.
	GoogleEventID string `json:"google_event_id,omitempty"`
	// SyncedAt holds the value of the "synced_at" field.
	SyncedAt time.Time `json:"synced_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TaskCalendarEventQuery when eager-loading is set.
	Edges        TaskCalendarEventEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TaskCalendarEventEdges holds the relations/edges for other nodes in the graph.
type TaskCalendarEventEdges struct {
	// Task holds the value of the task edge.
	Task *Task `json:"task,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskCalendarEventEdges) TaskOrErr() (*Task, error) {
	if e.Task != nil {
		return e.Task, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "task"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskCalendarEventEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TaskCalendarEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case taskcalendarevent.FieldGoogleEventID:
			values[i] = new(sql.NullString)
		case taskcalendarevent.FieldCreatedAt, taskcalendarevent.FieldUpdatedAt, taskcalendarevent.FieldSyncedAt:
			values[i] = new(sql.NullTime)
		case taskcalendarevent.FieldID, taskcalendarevent.FieldTaskID, taskcalendarevent.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TaskCalendarEvent fields.
func (_m *TaskCalendarEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case taskcalendarevent.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case taskcalendarevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case taskcalendarevent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case taskcalendarevent.FieldTaskID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value != nil {
				_m.TaskID = *value
			}
		case taskcalendarevent.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case taskcalendarevent.FieldGoogleEventID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field google_event_id", values[i])
			} else if value.Valid {
				_m.GoogleEventID = value.String
			}
		case taskcalendarevent.FieldSyncedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field synced_at", values[i])
			} else if value.Valid {
				_m.SyncedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TaskCalendarEvent.
// This includes values selected through modifiers, order, etc.
func (_m *TaskCalendarEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTask queries the "task" edge of the TaskCalendarEvent entity.
func (_m *TaskCalendarEvent) QueryTask() *TaskQuery {
	return NewTaskCalendarEventClient(_m.config).QueryTask(_m)
}

// QueryUser queries the "user" edge of the TaskCalendarEvent entity.
func (_m *TaskCalendarEvent) QueryUser() *UserQuery {
	return NewTaskCalendarEventClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this TaskCalendarEvent.
// Note that you need to call TaskCalendarEvent.Unwrap() before calling this method if this TaskCalendarEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TaskCalendarEvent) Update() *TaskCalendarEventUpdateOne {
	return NewTaskCalendarEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TaskCalendarEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TaskCalendarEvent) Unwrap() *TaskCalendarEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TaskCalendarEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TaskCalendarEvent) String() string {
	var builder strings.Builder
	builder.WriteString("TaskCalendarEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("task_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TaskID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("google_event_id=")
	builder.WriteString(_m.GoogleEventID)
	builder.WriteString(", ")
	builder.WriteString("synced_at=")
	builder.WriteString(_m.SyncedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TaskCalendarEvents is a parsable slice of TaskCalendarEvent.
type TaskCalendarEvents []*TaskCalendarEvent
