// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/osasadev-lab/aibo_pj/server/ent/attachment"
	"github.com/osasadev-lab/aibo_pj/server/ent/comment"
	"github.com/osasadev-lab/aibo_pj/server/ent/predicate"
	"github.com/osasadev-lab/aibo_pj/server/ent/project"
	"github.com/osasadev-lab/aibo_pj/server/ent/projectstatuscolumn"
	"github.com/osasadev-lab/aibo_pj/server/ent/section"
	"github.com/osasadev-lab/aibo_pj/server/ent/task"
	"github.com/osasadev-lab/aibo_pj/server/ent/taskassignee"
	"github.com/osasadev-lab/aibo_pj/server/ent/taskcalendarevent"
	"github.com/osasadev-lab/aibo_pj/server/ent/taskdependency"
	"github.com/osasadev-lab/aibo_pj/server/ent/tasktag"
	"github.com/osasadev-lab/aibo_pj/server/ent/user"
	"github.com/osasadev-lab/aibo_pj/server/ent/workspace"
)

// TaskUpdate is the builder for updating Task entities.
type TaskUpdate struct {
	config
	hooks    []Hook
	mutation *TaskMutation
}

// Where appends a list predicates to the TaskUpdate builder.
func (_u *TaskUpdate) Where(ps ...predicate.Task) *TaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaskUpdate) SetUpdatedAt(v time.Time) *TaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *TaskUpdate) SetWorkspaceID(v uuid.UUID) *TaskUpdate {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableWorkspaceID(v *uuid.UUID) *TaskUpdate {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *TaskUpdate) SetProjectID(v uuid.UUID) *TaskUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableProjectID(v *uuid.UUID) *TaskUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// ClearProjectID clears the value of the "project_id" field.
func (_u *TaskUpdate) ClearProjectID() *TaskUpdate {
	_u.mutation.ClearProjectID()
	return _u
}

// SetSectionID sets the "section_id" field.
func (_u *TaskUpdate) SetSectionID(v uuid.UUID) *TaskUpdate {
	_u.mutation.SetSectionID(v)
	return _u
}

// SetNillableSectionID sets the "section_id" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableSectionID(v *uuid.UUID) *TaskUpdate {
	if v != nil {
		_u.SetSectionID(*v)
	}
	return _u
}

// ClearSectionID clears the value of the "section_id" field.
func (_u *TaskUpdate) ClearSectionID() *TaskUpdate {
	_u.mutation.ClearSectionID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *TaskUpdate) SetStatus(v task.Status) *TaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableStatus(v *task.Status) *TaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStatusColumnID sets the "status_column_id" field.
func (_u *TaskUpdate) SetStatusColumnID(v uuid.UUID) *TaskUpdate {
	_u.mutation.SetStatusColumnID(v)
	return _u
}

// SetNillableStatusColumnID sets the "status_column_id" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableStatusColumnID(v *uuid.UUID) *TaskUpdate {
	if v != nil {
		_u.SetStatusColumnID(*v)
	}
	return _u
}

// ClearStatusColumnID clears the value of the "status_column_id" field.
func (_u *TaskUpdate) ClearStatusColumnID() *TaskUpdate {
	_u.mutation.ClearStatusColumnID()
	return _u
}

// SetParentTaskID sets the "parent_task_id" field.
func (_u *TaskUpdate) SetParentTaskID(v uuid.UUID) *TaskUpdate {
	_u.mutation.SetParentTaskID(v)
	return _u
}

// SetNillableParentTaskID sets the "parent_task_id" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableParentTaskID(v *uuid.UUID) *TaskUpdate {
	if v != nil {
		_u.SetParentTaskID(*v)
	}
	return _u
}

// ClearParentTaskID clears the value of the "parent_task_id" field.
func (_u *TaskUpdate) ClearParentTaskID() *TaskUpdate {
	_u.mutation.ClearParentTaskID()
	return _u
}

// SetTitle sets the "title" field.
func (_u *TaskUpdate) SetTitle(v string) *TaskUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableTitle(v *string) *TaskUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TaskUpdate) SetDescription(v string) *TaskUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableDescription(v *string) *TaskUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TaskUpdate) ClearDescription() *TaskUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TaskUpdate) SetPriority(v task.Priority) *TaskUpdate {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TaskUpdate) SetNillablePriority(v *task.Priority) *TaskUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// ClearPriority clears the value of the "priority" field.
func (_u *TaskUpdate) ClearPriority() *TaskUpdate {
	_u.mutation.ClearPriority()
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *TaskUpdate) SetStartDate(v time.Time) *TaskUpdate {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableStartDate(v *time.Time) *TaskUpdate {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// ClearStartDate clears the value of the "start_date" field.
func (_u *TaskUpdate) ClearStartDate() *TaskUpdate {
	_u.mutation.ClearStartDate()
	return _u
}

// SetDueDate sets the "due_date" field.
func (_u *TaskUpdate) SetDueDate(v time.Time) *TaskUpdate {
	_u.mutation.SetDueDate(v)
	return _u
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableDueDate(v *time.Time) *TaskUpdate {
	if v != nil {
		_u.SetDueDate(*v)
	}
	return _u
}

// ClearDueDate clears the value of the "due_date" field.
func (_u *TaskUpdate) ClearDueDate() *TaskUpdate {
	_u.mutation.ClearDueDate()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *TaskUpdate) SetCreatedBy(v uuid.UUID) *TaskUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableCreatedBy(v *uuid.UUID) *TaskUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_u *TaskUpdate) SetWorkspace(v *Workspace) *TaskUpdate {
	return _u.SetWorkspaceID(v.ID)
}

// SetProject sets the "project" edge to the Project entity.
func (_u *TaskUpdate) SetProject(v *Project) *TaskUpdate {
	return _u.SetProjectID(v.ID)
}

// SetSection sets the "section" edge to the Section entity.
func (_u *TaskUpdate) SetSection(v *Section) *TaskUpdate {
	return _u.SetSectionID(v.ID)
}

// SetStatusColumn sets the "status_column" edge to the ProjectStatusColumn entity.
func (_u *TaskUpdate) SetStatusColumn(v *ProjectStatusColumn) *TaskUpdate {
	return _u.SetStatusColumnID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *TaskUpdate) SetCreatorID(id uuid.UUID) *TaskUpdate {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *TaskUpdate) SetCreator(v *User) *TaskUpdate {
	return _u.SetCreatorID(v.ID)
}

// SetParentID sets the "parent" edge to the Task entity by ID.
func (_u *TaskUpdate) SetParentID(id uuid.UUID) *TaskUpdate {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the Task entity by ID if the given value is not nil.
func (_u *TaskUpdate) SetNillableParentID(id *uuid.UUID) *TaskUpdate {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the Task entity.
func (_u *TaskUpdate) SetParent(v *Task) *TaskUpdate {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Task entity by IDs.
func (_u *TaskUpdate) AddChildIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Task entity.
func (_u *TaskUpdate) AddChildren(v ...*Task) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// AddAssigneeIDs adds the "assignees" edge to the TaskAssignee entity by IDs.
func (_u *TaskUpdate) AddAssigneeIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.AddAssigneeIDs(ids...)
	return _u
}

// AddAssignees adds the "assignees" edges to the TaskAssignee entity.
func (_u *TaskUpdate) AddAssignees(v ...*TaskAssignee) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAssigneeIDs(ids...)
}

// AddCalendarEventIDs adds the "calendar_events" edge to the TaskCalendarEvent entity by IDs.
func (_u *TaskUpdate) AddCalendarEventIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.AddCalendarEventIDs(ids...)
	return _u
}

// AddCalendarEvents adds the "calendar_events" edges to the TaskCalendarEvent entity.
func (_u *TaskUpdate) AddCalendarEvents(v ...*TaskCalendarEvent) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCalendarEventIDs(ids...)
}

// AddDependencyIDs adds the "dependencies" edge to the TaskDependency entity by IDs.
func (_u *TaskUpdate) AddDependencyIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.AddDependencyIDs(ids...)
	return _u
}

// AddDependencies adds the "dependencies" edges to the TaskDependency entity.
func (_u *TaskUpdate) AddDependencies(v ...*TaskDependency) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDependencyIDs(ids...)
}

// AddDependentIDs adds the "dependents" edge to the TaskDependency entity by IDs.
func (_u *TaskUpdate) AddDependentIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.AddDependentIDs(ids...)
	return _u
}

// AddDependents adds the "dependents" edges to the TaskDependency entity.
func (_u *TaskUpdate) AddDependents(v ...*TaskDependency) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDependentIDs(ids...)
}

// AddTagIDs adds the "tags" edge to the TaskTag entity by IDs.
func (_u *TaskUpdate) AddTagIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.AddTagIDs(ids...)
	return _u
}

// AddTags adds the "tags" edges to the TaskTag entity.
func (_u *TaskUpdate) AddTags(v ...*TaskTag) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTagIDs(ids...)
}

// AddCommentIDs adds the "comments" edge to the Comment entity by IDs.
func (_u *TaskUpdate) AddCommentIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.AddCommentIDs(ids...)
	return _u
}

// AddComments adds the "comments" edges to the Comment entity.
func (_u *TaskUpdate) AddComments(v ...*Comment) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCommentIDs(ids...)
}

// AddAttachmentIDs adds the "attachments" edge to the Attachment entity by IDs.
func (_u *TaskUpdate) AddAttachmentIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the Attachment entity.
func (_u *TaskUpdate) AddAttachments(v ...*Attachment) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// Mutation returns the TaskMutation object of the builder.
func (_u *TaskUpdate) Mutation() *TaskMutation {
	return _u.mutation
}

// ClearWorkspace clears the "workspace" edge to the Workspace entity.
func (_u *TaskUpdate) ClearWorkspace() *TaskUpdate {
	_u.mutation.ClearWorkspace()
	return _u
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *TaskUpdate) ClearProject() *TaskUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearSection clears the "section" edge to the Section entity.
func (_u *TaskUpdate) ClearSection() *TaskUpdate {
	_u.mutation.ClearSection()
	return _u
}

// ClearStatusColumn clears the "status_column" edge to the ProjectStatusColumn entity.
func (_u *TaskUpdate) ClearStatusColumn() *TaskUpdate {
	_u.mutation.ClearStatusColumn()
	return _u
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *TaskUpdate) ClearCreator() *TaskUpdate {
	_u.mutation.ClearCreator()
	return _u
}

// ClearParent clears the "parent" edge to the Task entity.
func (_u *TaskUpdate) ClearParent() *TaskUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the Task entity.
func (_u *TaskUpdate) ClearChildren() *TaskUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Task entities by IDs.
func (_u *TaskUpdate) RemoveChildIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Task entities.
func (_u *TaskUpdate) RemoveChildren(v ...*Task) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearAssignees clears all "assignees" edges to the TaskAssignee entity.
func (_u *TaskUpdate) ClearAssignees() *TaskUpdate {
	_u.mutation.ClearAssignees()
	return _u
}

// RemoveAssigneeIDs removes the "assignees" edge to TaskAssignee entities by IDs.
func (_u *TaskUpdate) RemoveAssigneeIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.RemoveAssigneeIDs(ids...)
	return _u
}

// RemoveAssignees removes "assignees" edges to TaskAssignee entities.
func (_u *TaskUpdate) RemoveAssignees(v ...*TaskAssignee) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAssigneeIDs(ids...)
}

// ClearCalendarEvents clears all "calendar_events" edges to the TaskCalendarEvent entity.
func (_u *TaskUpdate) ClearCalendarEvents() *TaskUpdate {
	_u.mutation.ClearCalendarEvents()
	return _u
}

// RemoveCalendarEventIDs removes the "calendar_events" edge to TaskCalendarEvent entities by IDs.
func (_u *TaskUpdate) RemoveCalendarEventIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.RemoveCalendarEventIDs(ids...)
	return _u
}

// RemoveCalendarEvents removes "calendar_events" edges to TaskCalendarEvent entities.
func (_u *TaskUpdate) RemoveCalendarEvents(v ...*TaskCalendarEvent) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCalendarEventIDs(ids...)
}

// ClearDependencies clears all "dependencies" edges to the TaskDependency entity.
func (_u *TaskUpdate) ClearDependencies() *TaskUpdate {
	_u.mutation.ClearDependencies()
	return _u
}

// RemoveDependencyIDs removes the "dependencies" edge to TaskDependency entities by IDs.
func (_u *TaskUpdate) RemoveDependencyIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.RemoveDependencyIDs(ids...)
	return _u
}

// RemoveDependencies removes "dependencies" edges to TaskDependency entities.
func (_u *TaskUpdate) RemoveDependencies(v ...*TaskDependency) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDependencyIDs(ids...)
}

// ClearDependents clears all "dependents" edges to the TaskDependency entity.
func (_u *TaskUpdate) ClearDependents() *TaskUpdate {
	_u.mutation.ClearDependents()
	return _u
}

// RemoveDependentIDs removes the "dependents" edge to TaskDependency entities by IDs.
func (_u *TaskUpdate) RemoveDependentIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.RemoveDependentIDs(ids...)
	return _u
}

// RemoveDependents removes "dependents" edges to TaskDependency entities.
func (_u *TaskUpdate) RemoveDependents(v ...*TaskDependency) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDependentIDs(ids...)
}

// ClearTags clears all "tags" edges to the TaskTag entity.
func (_u *TaskUpdate) ClearTags() *TaskUpdate {
	_u.mutation.ClearTags()
	return _u
}

// RemoveTagIDs removes the "tags" edge to TaskTag entities by IDs.
func (_u *TaskUpdate) RemoveTagIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.RemoveTagIDs(ids...)
	return _u
}

// RemoveTags removes "tags" edges to TaskTag entities.
func (_u *TaskUpdate) RemoveTags(v ...*TaskTag) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTagIDs(ids...)
}

// ClearComments clears all "comments" edges to the Comment entity.
func (_u *TaskUpdate) ClearComments() *TaskUpdate {
	_u.mutation.ClearComments()
	return _u
}

// RemoveCommentIDs removes the "comments" edge to Comment entities by IDs.
func (_u *TaskUpdate) RemoveCommentIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.RemoveCommentIDs(ids...)
	return _u
}

// RemoveComments removes "comments" edges to Comment entities.
func (_u *TaskUpdate) RemoveComments(v ...*Comment) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCommentIDs(ids...)
}

// ClearAttachments clears all "attachments" edges to the Attachment entity.
func (_u *TaskUpdate) ClearAttachments() *TaskUpdate {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to Attachment entities by IDs.
func (_u *TaskUpdate) RemoveAttachmentIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to Attachment entities.
func (_u *TaskUpdate) RemoveAttachments(v ...*Attachment) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := task.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := task.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Task.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := task.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Task.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := task.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "Task.priority": %w`, err)}
		}
	}
	if _u.mutation.WorkspaceCleared() && len(_u.mutation.WorkspaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Task.workspace"`)
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Task.creator"`)
	}
	return nil
}

func (_u *TaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(task.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(task.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(task.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(task.FieldPriority, field.TypeEnum, value)
	}
	if _u.mutation.PriorityCleared() {
		_spec.ClearField(task.FieldPriority, field.TypeEnum)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(task.FieldStartDate, field.TypeTime, value)
	}
	if _u.mutation.StartDateCleared() {
		_spec.ClearField(task.FieldStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.DueDate(); ok {
		_spec.SetField(task.FieldDueDate, field.TypeTime, value)
	}
	if _u.mutation.DueDateCleared() {
		_spec.ClearField(task.FieldDueDate, field.TypeTime)
	}
	if _u.mutation.WorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   task.WorkspaceTable,
			Columns: []string{task.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   task.WorkspaceTable,
			Columns: []string{task.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   task.ProjectTable,
			Columns: []string{task.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   task.ProjectTable,
			Columns: []string{task.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   task.SectionTable,
			Columns: []string{task.SectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(section.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   task.SectionTable,
			Columns: []string{task.SectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(section.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StatusColumnCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   task.StatusColumnTable,
			Columns: []string{task.StatusColumnColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectstatuscolumn.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StatusColumnIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   task.StatusColumnTable,
			Columns: []string{task.StatusColumnColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectstatuscolumn.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   task.CreatorTable,
			Columns: []string{task.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   task.CreatorTable,
			Columns: []string{task.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ParentTable,
			Columns: []string{task.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ParentTable,
			Columns: []string{task.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ChildrenTable,
			Columns: []string{task.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ChildrenTable,
			Columns: []string{task.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ChildrenTable,
			Columns: []string{task.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssigneesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.AssigneesTable,
			Columns: []string{task.AssigneesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignee.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAssigneesIDs(); len(nodes) > 0 && !_u.mutation.AssigneesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.AssigneesTable,
			Columns: []string{task.AssigneesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssigneesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.AssigneesTable,
			Columns: []string{task.AssigneesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CalendarEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.CalendarEventsTable,
			Columns: []string{task.CalendarEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskcalendarevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCalendarEventsIDs(); len(nodes) > 0 && !_u.mutation.CalendarEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.CalendarEventsTable,
			Columns: []string{task.CalendarEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskcalendarevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CalendarEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.CalendarEventsTable,
			Columns: []string{task.CalendarEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskcalendarevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DependenciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.DependenciesTable,
			Columns: []string{task.DependenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskdependency.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDependenciesIDs(); len(nodes) > 0 && !_u.mutation.DependenciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.DependenciesTable,
			Columns: []string{task.DependenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskdependency.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DependenciesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.DependenciesTable,
			Columns: []string{task.DependenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskdependency.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DependentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.DependentsTable,
			Columns: []string{task.DependentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskdependency.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDependentsIDs(); len(nodes) > 0 && !_u.mutation.DependentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.DependentsTable,
			Columns: []string{task.DependentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskdependency.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DependentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.DependentsTable,
			Columns: []string{task.DependentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskdependency.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.TagsTable,
			Columns: []string{task.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tasktag.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagsIDs(); len(nodes) > 0 && !_u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.TagsTable,
			Columns: []string{task.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tasktag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.TagsTable,
			Columns: []string{task.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tasktag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.CommentsTable,
			Columns: []string{task.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCommentsIDs(); len(nodes) > 0 && !_u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.CommentsTable,
			Columns: []string{task.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.CommentsTable,
			Columns: []string{task.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.AttachmentsTable,
			Columns: []string{task.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.AttachmentsTable,
			Columns: []string{task.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.AttachmentsTable,
			Columns: []string{task.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaskUpdateOne is the builder for updating a single Task entity.
type TaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaskUpdateOne) SetUpdatedAt(v time.Time) *TaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *TaskUpdateOne) SetWorkspaceID(v uuid.UUID) *TaskUpdateOne {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableWorkspaceID(v *uuid.UUID) *TaskUpdateOne {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *TaskUpdateOne) SetProjectID(v uuid.UUID) *TaskUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableProjectID(v *uuid.UUID) *TaskUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// ClearProjectID clears the value of the "project_id" field.
func (_u *TaskUpdateOne) ClearProjectID() *TaskUpdateOne {
	_u.mutation.ClearProjectID()
	return _u
}

// SetSectionID sets the "section_id" field.
func (_u *TaskUpdateOne) SetSectionID(v uuid.UUID) *TaskUpdateOne {
	_u.mutation.SetSectionID(v)
	return _u
}

// SetNillableSectionID sets the "section_id" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableSectionID(v *uuid.UUID) *TaskUpdateOne {
	if v != nil {
		_u.SetSectionID(*v)
	}
	return _u
}

// ClearSectionID clears the value of the "section_id" field.
func (_u *TaskUpdateOne) ClearSectionID() *TaskUpdateOne {
	_u.mutation.ClearSectionID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *TaskUpdateOne) SetStatus(v task.Status) *TaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableStatus(v *task.Status) *TaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStatusColumnID sets the "status_column_id" field.
func (_u *TaskUpdateOne) SetStatusColumnID(v uuid.UUID) *TaskUpdateOne {
	_u.mutation.SetStatusColumnID(v)
	return _u
}

// SetNillableStatusColumnID sets the "status_column_id" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableStatusColumnID(v *uuid.UUID) *TaskUpdateOne {
	if v != nil {
		_u.SetStatusColumnID(*v)
	}
	return _u
}

// ClearStatusColumnID clears the value of the "status_column_id" field.
func (_u *TaskUpdateOne) ClearStatusColumnID() *TaskUpdateOne {
	_u.mutation.ClearStatusColumnID()
	return _u
}

// SetParentTaskID sets the "parent_task_id" field.
func (_u *TaskUpdateOne) SetParentTaskID(v uuid.UUID) *TaskUpdateOne {
	_u.mutation.SetParentTaskID(v)
	return _u
}

// SetNillableParentTaskID sets the "parent_task_id" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableParentTaskID(v *uuid.UUID) *TaskUpdateOne {
	if v != nil {
		_u.SetParentTaskID(*v)
	}
	return _u
}

// ClearParentTaskID clears the value of the "parent_task_id" field.
func (_u *TaskUpdateOne) ClearParentTaskID() *TaskUpdateOne {
	_u.mutation.ClearParentTaskID()
	return _u
}

// SetTitle sets the "title" field.
func (_u *TaskUpdateOne) SetTitle(v string) *TaskUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableTitle(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TaskUpdateOne) SetDescription(v string) *TaskUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableDescription(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TaskUpdateOne) ClearDescription() *TaskUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TaskUpdateOne) SetPriority(v task.Priority) *TaskUpdateOne {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillablePriority(v *task.Priority) *TaskUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// ClearPriority clears the value of the "priority" field.
func (_u *TaskUpdateOne) ClearPriority() *TaskUpdateOne {
	_u.mutation.ClearPriority()
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *TaskUpdateOne) SetStartDate(v time.Time) *TaskUpdateOne {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableStartDate(v *time.Time) *TaskUpdateOne {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// ClearStartDate clears the value of the "start_date" field.
func (_u *TaskUpdateOne) ClearStartDate() *TaskUpdateOne {
	_u.mutation.ClearStartDate()
	return _u
}

// SetDueDate sets the "due_date" field.
func (_u *TaskUpdateOne) SetDueDate(v time.Time) *TaskUpdateOne {
	_u.mutation.SetDueDate(v)
	return _u
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableDueDate(v *time.Time) *TaskUpdateOne {
	if v != nil {
		_u.SetDueDate(*v)
	}
	return _u
}

// ClearDueDate clears the value of the "due_date" field.
func (_u *TaskUpdateOne) ClearDueDate() *TaskUpdateOne {
	_u.mutation.ClearDueDate()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *TaskUpdateOne) SetCreatedBy(v uuid.UUID) *TaskUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableCreatedBy(v *uuid.UUID) *TaskUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_u *TaskUpdateOne) SetWorkspace(v *Workspace) *TaskUpdateOne {
	return _u.SetWorkspaceID(v.ID)
}

// SetProject sets the "project" edge to the Project entity.
func (_u *TaskUpdateOne) SetProject(v *Project) *TaskUpdateOne {
	return _u.SetProjectID(v.ID)
}

// SetSection sets the "section" edge to the Section entity.
func (_u *TaskUpdateOne) SetSection(v *Section) *TaskUpdateOne {
	return _u.SetSectionID(v.ID)
}

// SetStatusColumn sets the "status_column" edge to the ProjectStatusColumn entity.
func (_u *TaskUpdateOne) SetStatusColumn(v *ProjectStatusColumn) *TaskUpdateOne {
	return _u.SetStatusColumnID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *TaskUpdateOne) SetCreatorID(id uuid.UUID) *TaskUpdateOne {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *TaskUpdateOne) SetCreator(v *User) *TaskUpdateOne {
	return _u.SetCreatorID(v.ID)
}

// SetParentID sets the "parent" edge to the Task entity by ID.
func (_u *TaskUpdateOne) SetParentID(id uuid.UUID) *TaskUpdateOne {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the Task entity by ID if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableParentID(id *uuid.UUID) *TaskUpdateOne {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the Task entity.
func (_u *TaskUpdateOne) SetParent(v *Task) *TaskUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Task entity by IDs.
func (_u *TaskUpdateOne) AddChildIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Task entity.
func (_u *TaskUpdateOne) AddChildren(v ...*Task) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// AddAssigneeIDs adds the "assignees" edge to the TaskAssignee entity by IDs.
func (_u *TaskUpdateOne) AddAssigneeIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.AddAssigneeIDs(ids...)
	return _u
}

// AddAssignees adds the "assignees" edges to the TaskAssignee entity.
func (_u *TaskUpdateOne) AddAssignees(v ...*TaskAssignee) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAssigneeIDs(ids...)
}

// AddCalendarEventIDs adds the "calendar_events" edge to the TaskCalendarEvent entity by IDs.
func (_u *TaskUpdateOne) AddCalendarEventIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.AddCalendarEventIDs(ids...)
	return _u
}

// AddCalendarEvents adds the "calendar_events" edges to the TaskCalendarEvent entity.
func (_u *TaskUpdateOne) AddCalendarEvents(v ...*TaskCalendarEvent) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCalendarEventIDs(ids...)
}

// AddDependencyIDs adds the "dependencies" edge to the TaskDependency entity by IDs.
func (_u *TaskUpdateOne) AddDependencyIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.AddDependencyIDs(ids...)
	return _u
}

// AddDependencies adds the "dependencies" edges to the TaskDependency entity.
func (_u *TaskUpdateOne) AddDependencies(v ...*TaskDependency) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDependencyIDs(ids...)
}

// AddDependentIDs adds the "dependents" edge to the TaskDependency entity by IDs.
func (_u *TaskUpdateOne) AddDependentIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.AddDependentIDs(ids...)
	return _u
}

// AddDependents adds the "dependents" edges to the TaskDependency entity.
func (_u *TaskUpdateOne) AddDependents(v ...*TaskDependency) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDependentIDs(ids...)
}

// AddTagIDs adds the "tags" edge to the TaskTag entity by IDs.
func (_u *TaskUpdateOne) AddTagIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.AddTagIDs(ids...)
	return _u
}

// AddTags adds the "tags" edges to the TaskTag entity.
func (_u *TaskUpdateOne) AddTags(v ...*TaskTag) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTagIDs(ids...)
}

// AddCommentIDs adds the "comments" edge to the Comment entity by IDs.
func (_u *TaskUpdateOne) AddCommentIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.AddCommentIDs(ids...)
	return _u
}

// AddComments adds the "comments" edges to the Comment entity.
func (_u *TaskUpdateOne) AddComments(v ...*Comment) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCommentIDs(ids...)
}

// AddAttachmentIDs adds the "attachments" edge to the Attachment entity by IDs.
func (_u *TaskUpdateOne) AddAttachmentIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the Attachment entity.
func (_u *TaskUpdateOne) AddAttachments(v ...*Attachment) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// Mutation returns the TaskMutation object of the builder.
func (_u *TaskUpdateOne) Mutation() *TaskMutation {
	return _u.mutation
}

// ClearWorkspace clears the "workspace" edge to the Workspace entity.
func (_u *TaskUpdateOne) ClearWorkspace() *TaskUpdateOne {
	_u.mutation.ClearWorkspace()
	return _u
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *TaskUpdateOne) ClearProject() *TaskUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearSection clears the "section" edge to the Section entity.
func (_u *TaskUpdateOne) ClearSection() *TaskUpdateOne {
	_u.mutation.ClearSection()
	return _u
}

// ClearStatusColumn clears the "status_column" edge to the ProjectStatusColumn entity.
func (_u *TaskUpdateOne) ClearStatusColumn() *TaskUpdateOne {
	_u.mutation.ClearStatusColumn()
	return _u
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *TaskUpdateOne) ClearCreator() *TaskUpdateOne {
	_u.mutation.ClearCreator()
	return _u
}

// ClearParent clears the "parent" edge to the Task entity.
func (_u *TaskUpdateOne) ClearParent() *TaskUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the Task entity.
func (_u *TaskUpdateOne) ClearChildren() *TaskUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Task entities by IDs.
func (_u *TaskUpdateOne) RemoveChildIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Task entities.
func (_u *TaskUpdateOne) RemoveChildren(v ...*Task) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearAssignees clears all "assignees" edges to the TaskAssignee entity.
func (_u *TaskUpdateOne) ClearAssignees() *TaskUpdateOne {
	_u.mutation.ClearAssignees()
	return _u
}

// RemoveAssigneeIDs removes the "assignees" edge to TaskAssignee entities by IDs.
func (_u *TaskUpdateOne) RemoveAssigneeIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.RemoveAssigneeIDs(ids...)
	return _u
}

// RemoveAssignees removes "assignees" edges to TaskAssignee entities.
func (_u *TaskUpdateOne) RemoveAssignees(v ...*TaskAssignee) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAssigneeIDs(ids...)
}

// ClearCalendarEvents clears all "calendar_events" edges to the TaskCalendarEvent entity.
func (_u *TaskUpdateOne) ClearCalendarEvents() *TaskUpdateOne {
	_u.mutation.ClearCalendarEvents()
	return _u
}

// RemoveCalendarEventIDs removes the "calendar_events" edge to TaskCalendarEvent entities by IDs.
func (_u *TaskUpdateOne) RemoveCalendarEventIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.RemoveCalendarEventIDs(ids...)
	return _u
}

// RemoveCalendarEvents removes "calendar_events" edges to TaskCalendarEvent entities.
func (_u *TaskUpdateOne) RemoveCalendarEvents(v ...*TaskCalendarEvent) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCalendarEventIDs(ids...)
}

// ClearDependencies clears all "dependencies" edges to the TaskDependency entity.
func (_u *TaskUpdateOne) ClearDependencies() *TaskUpdateOne {
	_u.mutation.ClearDependencies()
	return _u
}

// RemoveDependencyIDs removes the "dependencies" edge to TaskDependency entities by IDs.
func (_u *TaskUpdateOne) RemoveDependencyIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.RemoveDependencyIDs(ids...)
	return _u
}

// RemoveDependencies removes "dependencies" edges to TaskDependency entities.
func (_u *TaskUpdateOne) RemoveDependencies(v ...*TaskDependency) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDependencyIDs(ids...)
}

// ClearDependents clears all "dependents" edges to the TaskDependency entity.
func (_u *TaskUpdateOne) ClearDependents() *TaskUpdateOne {
	_u.mutation.ClearDependents()
	return _u
}

// RemoveDependentIDs removes the "dependents" edge to TaskDependency entities by IDs.
func (_u *TaskUpdateOne) RemoveDependentIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.RemoveDependentIDs(ids...)
	return _u
}

// RemoveDependents removes "dependents" edges to TaskDependency entities.
func (_u *TaskUpdateOne) RemoveDependents(v ...*TaskDependency) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDependentIDs(ids...)
}

// ClearTags clears all "tags" edges to the TaskTag entity.
func (_u *TaskUpdateOne) ClearTags() *TaskUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// RemoveTagIDs removes the "tags" edge to TaskTag entities by IDs.
func (_u *TaskUpdateOne) RemoveTagIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.RemoveTagIDs(ids...)
	return _u
}

// RemoveTags removes "tags" edges to TaskTag entities.
func (_u *TaskUpdateOne) RemoveTags(v ...*TaskTag) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTagIDs(ids...)
}

// ClearComments clears all "comments" edges to the Comment entity.
func (_u *TaskUpdateOne) ClearComments() *TaskUpdateOne {
	_u.mutation.ClearComments()
	return _u
}

// RemoveCommentIDs removes the "comments" edge to Comment entities by IDs.
func (_u *TaskUpdateOne) RemoveCommentIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.RemoveCommentIDs(ids...)
	return _u
}

// RemoveComments removes "comments" edges to Comment entities.
func (_u *TaskUpdateOne) RemoveComments(v ...*Comment) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCommentIDs(ids...)
}

// ClearAttachments clears all "attachments" edges to the Attachment entity.
func (_u *TaskUpdateOne) ClearAttachments() *TaskUpdateOne {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to Attachment entities by IDs.
func (_u *TaskUpdateOne) RemoveAttachmentIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to Attachment entities.
func (_u *TaskUpdateOne) RemoveAttachments(v ...*Attachment) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// Where appends a list predicates to the TaskUpdate builder.
func (_u *TaskUpdateOne) Where(ps ...predicate.Task) *TaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaskUpdateOne) Select(field string, fields ...string) *TaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Task entity.
func (_u *TaskUpdateOne) Save(ctx context.Context) (*Task, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskUpdateOne) SaveX(ctx context.Context) *Task {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := task.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := task.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Task.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := task.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Task.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := task.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "Task.priority": %w`, err)}
		}
	}
	if _u.mutation.WorkspaceCleared() && len(_u.mutation.WorkspaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Task.workspace"`)
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Task.creator"`)
	}
	return nil
}

func (_u *TaskUpdateOne) sqlSave(ctx context.Context) (_node *Task, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Task.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, task.FieldID)
		for _, f := range fields {
			if !task.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != task.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(task.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(task.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(task.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(task.FieldPriority, field.TypeEnum, value)
	}
	if _u.mutation.PriorityCleared() {
		_spec.ClearField(task.FieldPriority, field.TypeEnum)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(task.FieldStartDate, field.TypeTime, value)
	}
	if _u.mutation.StartDateCleared() {
		_spec.ClearField(task.FieldStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.DueDate(); ok {
		_spec.SetField(task.FieldDueDate, field.TypeTime, value)
	}
	if _u.mutation.DueDateCleared() {
		_spec.ClearField(task.FieldDueDate, field.TypeTime)
	}
	if _u.mutation.WorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   task.WorkspaceTable,
			Columns: []string{task.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   task.WorkspaceTable,
			Columns: []string{task.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   task.ProjectTable,
			Columns: []string{task.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   task.ProjectTable,
			Columns: []string{task.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   task.SectionTable,
			Columns: []string{task.SectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(section.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   task.SectionTable,
			Columns: []string{task.SectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(section.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StatusColumnCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   task.StatusColumnTable,
			Columns: []string{task.StatusColumnColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectstatuscolumn.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StatusColumnIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   task.StatusColumnTable,
			Columns: []string{task.StatusColumnColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectstatuscolumn.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   task.CreatorTable,
			Columns: []string{task.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   task.CreatorTable,
			Columns: []string{task.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ParentTable,
			Columns: []string{task.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ParentTable,
			Columns: []string{task.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ChildrenTable,
			Columns: []string{task.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ChildrenTable,
			Columns: []string{task.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ChildrenTable,
			Columns: []string{task.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssigneesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.AssigneesTable,
			Columns: []string{task.AssigneesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignee.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAssigneesIDs(); len(nodes) > 0 && !_u.mutation.AssigneesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.AssigneesTable,
			Columns: []string{task.AssigneesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssigneesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.AssigneesTable,
			Columns: []string{task.AssigneesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CalendarEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.CalendarEventsTable,
			Columns: []string{task.CalendarEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskcalendarevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCalendarEventsIDs(); len(nodes) > 0 && !_u.mutation.CalendarEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.CalendarEventsTable,
			Columns: []string{task.CalendarEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskcalendarevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CalendarEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.CalendarEventsTable,
			Columns: []string{task.CalendarEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskcalendarevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DependenciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.DependenciesTable,
			Columns: []string{task.DependenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskdependency.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDependenciesIDs(); len(nodes) > 0 && !_u.mutation.DependenciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.DependenciesTable,
			Columns: []string{task.DependenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskdependency.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DependenciesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.DependenciesTable,
			Columns: []string{task.DependenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskdependency.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DependentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.DependentsTable,
			Columns: []string{task.DependentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskdependency.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDependentsIDs(); len(nodes) > 0 && !_u.mutation.DependentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.DependentsTable,
			Columns: []string{task.DependentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskdependency.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DependentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.DependentsTable,
			Columns: []string{task.DependentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskdependency.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.TagsTable,
			Columns: []string{task.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tasktag.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagsIDs(); len(nodes) > 0 && !_u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.TagsTable,
			Columns: []string{task.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tasktag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.TagsTable,
			Columns: []string{task.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tasktag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.CommentsTable,
			Columns: []string{task.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCommentsIDs(); len(nodes) > 0 && !_u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.CommentsTable,
			Columns: []string{task.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.CommentsTable,
			Columns: []string{task.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.AttachmentsTable,
			Columns: []string{task.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.AttachmentsTable,
			Columns: []string{task.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   task.AttachmentsTable,
			Columns: []string{task.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Task{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
