// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/osasadev-lab/aibo_pj/server/ent/predicate"
	"github.com/osasadev-lab/aibo_pj/server/ent/taskmemo"
	"github.com/osasadev-lab/aibo_pj/server/ent/taskmemoattachment"
	"github.com/osasadev-lab/aibo_pj/server/ent/user"
)

// TaskMemoAttachmentQuery is the builder for querying TaskMemoAttachment entities.
type TaskMemoAttachmentQuery struct {
	config
	ctx          *QueryContext
	order        []taskmemoattachment.OrderOption
	inters       []Interceptor
	predicates   []predicate.TaskMemoAttachment
	withMemo     *TaskMemoQuery
	withUploader *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TaskMemoAttachmentQuery builder.
func (_q *TaskMemoAttachmentQuery) Where(ps ...predicate.TaskMemoAttachment) *TaskMemoAttachmentQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *TaskMemoAttachmentQuery) Limit(limit int) *TaskMemoAttachmentQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *TaskMemoAttachmentQuery) Offset(offset int) *TaskMemoAttachmentQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *TaskMemoAttachmentQuery) Unique(unique bool) *TaskMemoAttachmentQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *TaskMemoAttachmentQuery) Order(o ...taskmemoattachment.OrderOption) *TaskMemoAttachmentQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryMemo chains the current query on the "memo" edge.
func (_q *TaskMemoAttachmentQuery) QueryMemo() *TaskMemoQuery {
	query := (&TaskMemoClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(taskmemoattachment.Table, taskmemoattachment.FieldID, selector),
			sqlgraph.To(taskmemo.Table, taskmemo.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, taskmemoattachment.MemoTable, taskmemoattachment.MemoColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUploader chains the current query on the "uploader" edge.
func (_q *TaskMemoAttachmentQuery) QueryUploader() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(taskmemoattachment.Table, taskmemoattachment.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, taskmemoattachment.UploaderTable, taskmemoattachment.UploaderColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TaskMemoAttachment entity from the query.
// Returns a *NotFoundError when no TaskMemoAttachment was found.
func (_q *TaskMemoAttachmentQuery) First(ctx context.Context) (*TaskMemoAttachment, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{taskmemoattachment.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *TaskMemoAttachmentQuery) FirstX(ctx context.Context) *TaskMemoAttachment {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TaskMemoAttachment ID from the query.
// Returns a *NotFoundError when no TaskMemoAttachment ID was found.
func (_q *TaskMemoAttachmentQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{taskmemoattachment.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *TaskMemoAttachmentQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TaskMemoAttachment entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TaskMemoAttachment entity is found.
// Returns a *NotFoundError when no TaskMemoAttachment entities are found.
func (_q *TaskMemoAttachmentQuery) Only(ctx context.Context) (*TaskMemoAttachment, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{taskmemoattachment.Label}
	default:
		return nil, &NotSingularError{taskmemoattachment.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *TaskMemoAttachmentQuery) OnlyX(ctx context.Context) *TaskMemoAttachment {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TaskMemoAttachment ID in the query.
// Returns a *NotSingularError when more than one TaskMemoAttachment ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *TaskMemoAttachmentQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{taskmemoattachment.Label}
	default:
		err = &NotSingularError{taskmemoattachment.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *TaskMemoAttachmentQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TaskMemoAttachments.
func (_q *TaskMemoAttachmentQuery) All(ctx context.Context) ([]*TaskMemoAttachment, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TaskMemoAttachment, *TaskMemoAttachmentQuery]()
	return withInterceptors[[]*TaskMemoAttachment](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *TaskMemoAttachmentQuery) AllX(ctx context.Context) []*TaskMemoAttachment {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TaskMemoAttachment IDs.
func (_q *TaskMemoAttachmentQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(taskmemoattachment.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *TaskMemoAttachmentQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *TaskMemoAttachmentQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*TaskMemoAttachmentQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *TaskMemoAttachmentQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *TaskMemoAttachmentQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *TaskMemoAttachmentQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TaskMemoAttachmentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *TaskMemoAttachmentQuery) Clone() *TaskMemoAttachmentQuery {
	if _q == nil {
		return nil
	}
	return &TaskMemoAttachmentQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]taskmemoattachment.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.TaskMemoAttachment{}, _q.predicates...),
		withMemo:     _q.withMemo.Clone(),
		withUploader: _q.withUploader.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithMemo tells the query-builder to eager-load the nodes that are connected to
// the "memo" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TaskMemoAttachmentQuery) WithMemo(opts ...func(*TaskMemoQuery)) *TaskMemoAttachmentQuery {
	query := (&TaskMemoClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMemo = query
	return _q
}

// WithUploader tells the query-builder to eager-load the nodes that are connected to
// the "uploader" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TaskMemoAttachmentQuery) WithUploader(opts ...func(*UserQuery)) *TaskMemoAttachmentQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUploader = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TaskMemoAttachment.Query().
//		GroupBy(taskmemoattachment.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *TaskMemoAttachmentQuery) GroupBy(field string, fields ...string) *TaskMemoAttachmentGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TaskMemoAttachmentGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = taskmemoattachment.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.TaskMemoAttachment.Query().
//		Select(taskmemoattachment.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *TaskMemoAttachmentQuery) Select(fields ...string) *TaskMemoAttachmentSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &TaskMemoAttachmentSelect{TaskMemoAttachmentQuery: _q}
	sbuild.label = taskmemoattachment.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TaskMemoAttachmentSelect configured with the given aggregations.
func (_q *TaskMemoAttachmentQuery) Aggregate(fns ...AggregateFunc) *TaskMemoAttachmentSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *TaskMemoAttachmentQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !taskmemoattachment.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *TaskMemoAttachmentQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TaskMemoAttachment, error) {
	var (
		nodes       = []*TaskMemoAttachment{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withMemo != nil,
			_q.withUploader != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TaskMemoAttachment).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TaskMemoAttachment{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withMemo; query != nil {
		if err := _q.loadMemo(ctx, query, nodes, nil,
			func(n *TaskMemoAttachment, e *TaskMemo) { n.Edges.Memo = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUploader; query != nil {
		if err := _q.loadUploader(ctx, query, nodes, nil,
			func(n *TaskMemoAttachment, e *User) { n.Edges.Uploader = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *TaskMemoAttachmentQuery) loadMemo(ctx context.Context, query *TaskMemoQuery, nodes []*TaskMemoAttachment, init func(*TaskMemoAttachment), assign func(*TaskMemoAttachment, *TaskMemo)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*TaskMemoAttachment)
	for i := range nodes {
		fk := nodes[i].TaskMemoID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(taskmemo.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "task_memo_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *TaskMemoAttachmentQuery) loadUploader(ctx context.Context, query *UserQuery, nodes []*TaskMemoAttachment, init func(*TaskMemoAttachment), assign func(*TaskMemoAttachment, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*TaskMemoAttachment)
	for i := range nodes {
		fk := nodes[i].UploadedBy
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "uploaded_by" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *TaskMemoAttachmentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *TaskMemoAttachmentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(taskmemoattachment.Table, taskmemoattachment.Columns, sqlgraph.NewFieldSpec(taskmemoattachment.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, taskmemoattachment.FieldID)
		for i := range fields {
			if fields[i] != taskmemoattachment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withMemo != nil {
			_spec.Node.AddColumnOnce(taskmemoattachment.FieldTaskMemoID)
		}
		if _q.withUploader != nil {
			_spec.Node.AddColumnOnce(taskmemoattachment.FieldUploadedBy)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *TaskMemoAttachmentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(taskmemoattachment.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = taskmemoattachment.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TaskMemoAttachmentGroupBy is the group-by builder for TaskMemoAttachment entities.
type TaskMemoAttachmentGroupBy struct {
	selector
	build *TaskMemoAttachmentQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *TaskMemoAttachmentGroupBy) Aggregate(fns ...AggregateFunc) *TaskMemoAttachmentGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *TaskMemoAttachmentGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TaskMemoAttachmentQuery, *TaskMemoAttachmentGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *TaskMemoAttachmentGroupBy) sqlScan(ctx context.Context, root *TaskMemoAttachmentQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TaskMemoAttachmentSelect is the builder for selecting fields of TaskMemoAttachment entities.
type TaskMemoAttachmentSelect struct {
	*TaskMemoAttachmentQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *TaskMemoAttachmentSelect) Aggregate(fns ...AggregateFunc) *TaskMemoAttachmentSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *TaskMemoAttachmentSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TaskMemoAttachmentQuery, *TaskMemoAttachmentSelect](ctx, _s.TaskMemoAttachmentQuery, _s, _s.inters, v)
}

func (_s *TaskMemoAttachmentSelect) sqlScan(ctx context.Context, root *TaskMemoAttachmentQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
