// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/osasadev-lab/aibo_pj/server/ent/activitylog"
	"github.com/osasadev-lab/aibo_pj/server/ent/attachment"
	"github.com/osasadev-lab/aibo_pj/server/ent/comment"
	"github.com/osasadev-lab/aibo_pj/server/ent/commentmention"
	"github.com/osasadev-lab/aibo_pj/server/ent/notification"
	"github.com/osasadev-lab/aibo_pj/server/ent/predicate"
	"github.com/osasadev-lab/aibo_pj/server/ent/project"
	"github.com/osasadev-lab/aibo_pj/server/ent/projectmember"
	"github.com/osasadev-lab/aibo_pj/server/ent/task"
	"github.com/osasadev-lab/aibo_pj/server/ent/taskassignee"
	"github.com/osasadev-lab/aibo_pj/server/ent/taskcalendarevent"
	"github.com/osasadev-lab/aibo_pj/server/ent/user"
	"github.com/osasadev-lab/aibo_pj/server/ent/workspaceinvitation"
	"github.com/osasadev-lab/aibo_pj/server/ent/workspacemember"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdate) SetUpdatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGoogleSub sets the "google_sub" field.
func (_u *UserUpdate) SetGoogleSub(v string) *UserUpdate {
	_u.mutation.SetGoogleSub(v)
	return _u
}

// SetNillableGoogleSub sets the "google_sub" field if the given value is not nil.
func (_u *UserUpdate) SetNillableGoogleSub(v *string) *UserUpdate {
	if v != nil {
		_u.SetGoogleSub(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *UserUpdate) SetName(v string) *UserUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableName(v *string) *UserUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAvatarURL sets the "avatar_url" field.
func (_u *UserUpdate) SetAvatarURL(v string) *UserUpdate {
	_u.mutation.SetAvatarURL(v)
	return _u
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAvatarURL(v *string) *UserUpdate {
	if v != nil {
		_u.SetAvatarURL(*v)
	}
	return _u
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (_u *UserUpdate) ClearAvatarURL() *UserUpdate {
	_u.mutation.ClearAvatarURL()
	return _u
}

// SetGoogleRefreshToken sets the "google_refresh_token" field.
func (_u *UserUpdate) SetGoogleRefreshToken(v string) *UserUpdate {
	_u.mutation.SetGoogleRefreshToken(v)
	return _u
}

// SetNillableGoogleRefreshToken sets the "google_refresh_token" field if the given value is not nil.
func (_u *UserUpdate) SetNillableGoogleRefreshToken(v *string) *UserUpdate {
	if v != nil {
		_u.SetGoogleRefreshToken(*v)
	}
	return _u
}

// ClearGoogleRefreshToken clears the value of the "google_refresh_token" field.
func (_u *UserUpdate) ClearGoogleRefreshToken() *UserUpdate {
	_u.mutation.ClearGoogleRefreshToken()
	return _u
}

// SetCalendarSyncEnabled sets the "calendar_sync_enabled" field.
func (_u *UserUpdate) SetCalendarSyncEnabled(v bool) *UserUpdate {
	_u.mutation.SetCalendarSyncEnabled(v)
	return _u
}

// SetNillableCalendarSyncEnabled sets the "calendar_sync_enabled" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCalendarSyncEnabled(v *bool) *UserUpdate {
	if v != nil {
		_u.SetCalendarSyncEnabled(*v)
	}
	return _u
}

// SetCalendarSyncMode sets the "calendar_sync_mode" field.
func (_u *UserUpdate) SetCalendarSyncMode(v user.CalendarSyncMode) *UserUpdate {
	_u.mutation.SetCalendarSyncMode(v)
	return _u
}

// SetNillableCalendarSyncMode sets the "calendar_sync_mode" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCalendarSyncMode(v *user.CalendarSyncMode) *UserUpdate {
	if v != nil {
		_u.SetCalendarSyncMode(*v)
	}
	return _u
}

// ClearCalendarSyncMode clears the value of the "calendar_sync_mode" field.
func (_u *UserUpdate) ClearCalendarSyncMode() *UserUpdate {
	_u.mutation.ClearCalendarSyncMode()
	return _u
}

// AddWorkspaceMemberIDs adds the "workspace_members" edge to the WorkspaceMember entity by IDs.
func (_u *UserUpdate) AddWorkspaceMemberIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddWorkspaceMemberIDs(ids...)
	return _u
}

// AddWorkspaceMembers adds the "workspace_members" edges to the WorkspaceMember entity.
func (_u *UserUpdate) AddWorkspaceMembers(v ...*WorkspaceMember) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWorkspaceMemberIDs(ids...)
}

// AddProjectMemberIDs adds the "project_members" edge to the ProjectMember entity by IDs.
func (_u *UserUpdate) AddProjectMemberIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddProjectMemberIDs(ids...)
	return _u
}

// AddProjectMembers adds the "project_members" edges to the ProjectMember entity.
func (_u *UserUpdate) AddProjectMembers(v ...*ProjectMember) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProjectMemberIDs(ids...)
}

// AddCreatedProjectIDs adds the "created_projects" edge to the Project entity by IDs.
func (_u *UserUpdate) AddCreatedProjectIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddCreatedProjectIDs(ids...)
	return _u
}

// AddCreatedProjects adds the "created_projects" edges to the Project entity.
func (_u *UserUpdate) AddCreatedProjects(v ...*Project) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCreatedProjectIDs(ids...)
}

// AddCreatedTaskIDs adds the "created_tasks" edge to the Task entity by IDs.
func (_u *UserUpdate) AddCreatedTaskIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddCreatedTaskIDs(ids...)
	return _u
}

// AddCreatedTasks adds the "created_tasks" edges to the Task entity.
func (_u *UserUpdate) AddCreatedTasks(v ...*Task) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCreatedTaskIDs(ids...)
}

// AddTaskAssigneeIDs adds the "task_assignees" edge to the TaskAssignee entity by IDs.
func (_u *UserUpdate) AddTaskAssigneeIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddTaskAssigneeIDs(ids...)
	return _u
}

// AddTaskAssignees adds the "task_assignees" edges to the TaskAssignee entity.
func (_u *UserUpdate) AddTaskAssignees(v ...*TaskAssignee) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskAssigneeIDs(ids...)
}

// AddCalendarEventIDs adds the "calendar_events" edge to the TaskCalendarEvent entity by IDs.
func (_u *UserUpdate) AddCalendarEventIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddCalendarEventIDs(ids...)
	return _u
}

// AddCalendarEvents adds the "calendar_events" edges to the TaskCalendarEvent entity.
func (_u *UserUpdate) AddCalendarEvents(v ...*TaskCalendarEvent) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCalendarEventIDs(ids...)
}

// AddCommentIDs adds the "comments" edge to the Comment entity by IDs.
func (_u *UserUpdate) AddCommentIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddCommentIDs(ids...)
	return _u
}

// AddComments adds the "comments" edges to the Comment entity.
func (_u *UserUpdate) AddComments(v ...*Comment) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCommentIDs(ids...)
}

// AddCommentMentionIDs adds the "comment_mentions" edge to the CommentMention entity by IDs.
func (_u *UserUpdate) AddCommentMentionIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddCommentMentionIDs(ids...)
	return _u
}

// AddCommentMentions adds the "comment_mentions" edges to the CommentMention entity.
func (_u *UserUpdate) AddCommentMentions(v ...*CommentMention) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCommentMentionIDs(ids...)
}

// AddAttachmentIDs adds the "attachments" edge to the Attachment entity by IDs.
func (_u *UserUpdate) AddAttachmentIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the Attachment entity.
func (_u *UserUpdate) AddAttachments(v ...*Attachment) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// AddActivityLogIDs adds the "activity_logs" edge to the ActivityLog entity by IDs.
func (_u *UserUpdate) AddActivityLogIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddActivityLogIDs(ids...)
	return _u
}

// AddActivityLogs adds the "activity_logs" edges to the ActivityLog entity.
func (_u *UserUpdate) AddActivityLogs(v ...*ActivityLog) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddActivityLogIDs(ids...)
}

// AddNotificationIDs adds the "notifications" edge to the Notification entity by IDs.
func (_u *UserUpdate) AddNotificationIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddNotificationIDs(ids...)
	return _u
}

// AddNotifications adds the "notifications" edges to the Notification entity.
func (_u *UserUpdate) AddNotifications(v ...*Notification) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNotificationIDs(ids...)
}

// AddSentInvitationIDs adds the "sent_invitations" edge to the WorkspaceInvitation entity by IDs.
func (_u *UserUpdate) AddSentInvitationIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddSentInvitationIDs(ids...)
	return _u
}

// AddSentInvitations adds the "sent_invitations" edges to the WorkspaceInvitation entity.
func (_u *UserUpdate) AddSentInvitations(v ...*WorkspaceInvitation) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSentInvitationIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearWorkspaceMembers clears all "workspace_members" edges to the WorkspaceMember entity.
func (_u *UserUpdate) ClearWorkspaceMembers() *UserUpdate {
	_u.mutation.ClearWorkspaceMembers()
	return _u
}

// RemoveWorkspaceMemberIDs removes the "workspace_members" edge to WorkspaceMember entities by IDs.
func (_u *UserUpdate) RemoveWorkspaceMemberIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveWorkspaceMemberIDs(ids...)
	return _u
}

// RemoveWorkspaceMembers removes "workspace_members" edges to WorkspaceMember entities.
func (_u *UserUpdate) RemoveWorkspaceMembers(v ...*WorkspaceMember) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWorkspaceMemberIDs(ids...)
}

// ClearProjectMembers clears all "project_members" edges to the ProjectMember entity.
func (_u *UserUpdate) ClearProjectMembers() *UserUpdate {
	_u.mutation.ClearProjectMembers()
	return _u
}

// RemoveProjectMemberIDs removes the "project_members" edge to ProjectMember entities by IDs.
func (_u *UserUpdate) RemoveProjectMemberIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveProjectMemberIDs(ids...)
	return _u
}

// RemoveProjectMembers removes "project_members" edges to ProjectMember entities.
func (_u *UserUpdate) RemoveProjectMembers(v ...*ProjectMember) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProjectMemberIDs(ids...)
}

// ClearCreatedProjects clears all "created_projects" edges to the Project entity.
func (_u *UserUpdate) ClearCreatedProjects() *UserUpdate {
	_u.mutation.ClearCreatedProjects()
	return _u
}

// RemoveCreatedProjectIDs removes the "created_projects" edge to Project entities by IDs.
func (_u *UserUpdate) RemoveCreatedProjectIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveCreatedProjectIDs(ids...)
	return _u
}

// RemoveCreatedProjects removes "created_projects" edges to Project entities.
func (_u *UserUpdate) RemoveCreatedProjects(v ...*Project) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCreatedProjectIDs(ids...)
}

// ClearCreatedTasks clears all "created_tasks" edges to the Task entity.
func (_u *UserUpdate) ClearCreatedTasks() *UserUpdate {
	_u.mutation.ClearCreatedTasks()
	return _u
}

// RemoveCreatedTaskIDs removes the "created_tasks" edge to Task entities by IDs.
func (_u *UserUpdate) RemoveCreatedTaskIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveCreatedTaskIDs(ids...)
	return _u
}

// RemoveCreatedTasks removes "created_tasks" edges to Task entities.
func (_u *UserUpdate) RemoveCreatedTasks(v ...*Task) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCreatedTaskIDs(ids...)
}

// ClearTaskAssignees clears all "task_assignees" edges to the TaskAssignee entity.
func (_u *UserUpdate) ClearTaskAssignees() *UserUpdate {
	_u.mutation.ClearTaskAssignees()
	return _u
}

// RemoveTaskAssigneeIDs removes the "task_assignees" edge to TaskAssignee entities by IDs.
func (_u *UserUpdate) RemoveTaskAssigneeIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveTaskAssigneeIDs(ids...)
	return _u
}

// RemoveTaskAssignees removes "task_assignees" edges to TaskAssignee entities.
func (_u *UserUpdate) RemoveTaskAssignees(v ...*TaskAssignee) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskAssigneeIDs(ids...)
}

// ClearCalendarEvents clears all "calendar_events" edges to the TaskCalendarEvent entity.
func (_u *UserUpdate) ClearCalendarEvents() *UserUpdate {
	_u.mutation.ClearCalendarEvents()
	return _u
}

// RemoveCalendarEventIDs removes the "calendar_events" edge to TaskCalendarEvent entities by IDs.
func (_u *UserUpdate) RemoveCalendarEventIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveCalendarEventIDs(ids...)
	return _u
}

// RemoveCalendarEvents removes "calendar_events" edges to TaskCalendarEvent entities.
func (_u *UserUpdate) RemoveCalendarEvents(v ...*TaskCalendarEvent) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCalendarEventIDs(ids...)
}

// ClearComments clears all "comments" edges to the Comment entity.
func (_u *UserUpdate) ClearComments() *UserUpdate {
	_u.mutation.ClearComments()
	return _u
}

// RemoveCommentIDs removes the "comments" edge to Comment entities by IDs.
func (_u *UserUpdate) RemoveCommentIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveCommentIDs(ids...)
	return _u
}

// RemoveComments removes "comments" edges to Comment entities.
func (_u *UserUpdate) RemoveComments(v ...*Comment) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCommentIDs(ids...)
}

// ClearCommentMentions clears all "comment_mentions" edges to the CommentMention entity.
func (_u *UserUpdate) ClearCommentMentions() *UserUpdate {
	_u.mutation.ClearCommentMentions()
	return _u
}

// RemoveCommentMentionIDs removes the "comment_mentions" edge to CommentMention entities by IDs.
func (_u *UserUpdate) RemoveCommentMentionIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveCommentMentionIDs(ids...)
	return _u
}

// RemoveCommentMentions removes "comment_mentions" edges to CommentMention entities.
func (_u *UserUpdate) RemoveCommentMentions(v ...*CommentMention) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCommentMentionIDs(ids...)
}

// ClearAttachments clears all "attachments" edges to the Attachment entity.
func (_u *UserUpdate) ClearAttachments() *UserUpdate {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to Attachment entities by IDs.
func (_u *UserUpdate) RemoveAttachmentIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to Attachment entities.
func (_u *UserUpdate) RemoveAttachments(v ...*Attachment) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// ClearActivityLogs clears all "activity_logs" edges to the ActivityLog entity.
func (_u *UserUpdate) ClearActivityLogs() *UserUpdate {
	_u.mutation.ClearActivityLogs()
	return _u
}

// RemoveActivityLogIDs removes the "activity_logs" edge to ActivityLog entities by IDs.
func (_u *UserUpdate) RemoveActivityLogIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveActivityLogIDs(ids...)
	return _u
}

// RemoveActivityLogs removes "activity_logs" edges to ActivityLog entities.
func (_u *UserUpdate) RemoveActivityLogs(v ...*ActivityLog) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveActivityLogIDs(ids...)
}

// ClearNotifications clears all "notifications" edges to the Notification entity.
func (_u *UserUpdate) ClearNotifications() *UserUpdate {
	_u.mutation.ClearNotifications()
	return _u
}

// RemoveNotificationIDs removes the "notifications" edge to Notification entities by IDs.
func (_u *UserUpdate) RemoveNotificationIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveNotificationIDs(ids...)
	return _u
}

// RemoveNotifications removes "notifications" edges to Notification entities.
func (_u *UserUpdate) RemoveNotifications(v ...*Notification) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNotificationIDs(ids...)
}

// ClearSentInvitations clears all "sent_invitations" edges to the WorkspaceInvitation entity.
func (_u *UserUpdate) ClearSentInvitations() *UserUpdate {
	_u.mutation.ClearSentInvitations()
	return _u
}

// RemoveSentInvitationIDs removes the "sent_invitations" edge to WorkspaceInvitation entities by IDs.
func (_u *UserUpdate) RemoveSentInvitationIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveSentInvitationIDs(ids...)
	return _u
}

// RemoveSentInvitations removes "sent_invitations" edges to WorkspaceInvitation entities.
func (_u *UserUpdate) RemoveSentInvitations(v ...*WorkspaceInvitation) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSentInvitationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.GoogleSub(); ok {
		if err := user.GoogleSubValidator(v); err != nil {
			return &ValidationError{Name: "google_sub", err: fmt.Errorf(`ent: validator failed for field "User.google_sub": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := user.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "User.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CalendarSyncMode(); ok {
		if err := user.CalendarSyncModeValidator(v); err != nil {
			return &ValidationError{Name: "calendar_sync_mode", err: fmt.Errorf(`ent: validator failed for field "User.calendar_sync_mode": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GoogleSub(); ok {
		_spec.SetField(user.FieldGoogleSub, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AvatarURL(); ok {
		_spec.SetField(user.FieldAvatarURL, field.TypeString, value)
	}
	if _u.mutation.AvatarURLCleared() {
		_spec.ClearField(user.FieldAvatarURL, field.TypeString)
	}
	if value, ok := _u.mutation.GoogleRefreshToken(); ok {
		_spec.SetField(user.FieldGoogleRefreshToken, field.TypeString, value)
	}
	if _u.mutation.GoogleRefreshTokenCleared() {
		_spec.ClearField(user.FieldGoogleRefreshToken, field.TypeString)
	}
	if value, ok := _u.mutation.CalendarSyncEnabled(); ok {
		_spec.SetField(user.FieldCalendarSyncEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CalendarSyncMode(); ok {
		_spec.SetField(user.FieldCalendarSyncMode, field.TypeEnum, value)
	}
	if _u.mutation.CalendarSyncModeCleared() {
		_spec.ClearField(user.FieldCalendarSyncMode, field.TypeEnum)
	}
	if _u.mutation.WorkspaceMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.WorkspaceMembersTable,
			Columns: []string{user.WorkspaceMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspacemember.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWorkspaceMembersIDs(); len(nodes) > 0 && !_u.mutation.WorkspaceMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.WorkspaceMembersTable,
			Columns: []string{user.WorkspaceMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspacemember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkspaceMembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.WorkspaceMembersTable,
			Columns: []string{user.WorkspaceMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspacemember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProjectMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.ProjectMembersTable,
			Columns: []string{user.ProjectMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectmember.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProjectMembersIDs(); len(nodes) > 0 && !_u.mutation.ProjectMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.ProjectMembersTable,
			Columns: []string{user.ProjectMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectmember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectMembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.ProjectMembersTable,
			Columns: []string{user.ProjectMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectmember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatedProjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CreatedProjectsTable,
			Columns: []string{user.CreatedProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCreatedProjectsIDs(); len(nodes) > 0 && !_u.mutation.CreatedProjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CreatedProjectsTable,
			Columns: []string{user.CreatedProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedProjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CreatedProjectsTable,
			Columns: []string{user.CreatedProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatedTasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CreatedTasksTable,
			Columns: []string{user.CreatedTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCreatedTasksIDs(); len(nodes) > 0 && !_u.mutation.CreatedTasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CreatedTasksTable,
			Columns: []string{user.CreatedTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedTasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CreatedTasksTable,
			Columns: []string{user.CreatedTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TaskAssigneesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.TaskAssigneesTable,
			Columns: []string{user.TaskAssigneesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignee.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTaskAssigneesIDs(); len(nodes) > 0 && !_u.mutation.TaskAssigneesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.TaskAssigneesTable,
			Columns: []string{user.TaskAssigneesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskAssigneesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.TaskAssigneesTable,
			Columns: []string{user.TaskAssigneesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CalendarEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CalendarEventsTable,
			Columns: []string{user.CalendarEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskcalendarevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCalendarEventsIDs(); len(nodes) > 0 && !_u.mutation.CalendarEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CalendarEventsTable,
			Columns: []string{user.CalendarEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskcalendarevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CalendarEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CalendarEventsTable,
			Columns: []string{user.CalendarEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskcalendarevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CommentsTable,
			Columns: []string{user.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCommentsIDs(); len(nodes) > 0 && !_u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CommentsTable,
			Columns: []string{user.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CommentsTable,
			Columns: []string{user.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CommentMentionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CommentMentionsTable,
			Columns: []string{user.CommentMentionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(commentmention.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCommentMentionsIDs(); len(nodes) > 0 && !_u.mutation.CommentMentionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CommentMentionsTable,
			Columns: []string{user.CommentMentionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(commentmention.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommentMentionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CommentMentionsTable,
			Columns: []string{user.CommentMentionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(commentmention.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.AttachmentsTable,
			Columns: []string{user.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.AttachmentsTable,
			Columns: []string{user.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.AttachmentsTable,
			Columns: []string{user.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ActivityLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.ActivityLogsTable,
			Columns: []string{user.ActivityLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activitylog.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedActivityLogsIDs(); len(nodes) > 0 && !_u.mutation.ActivityLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.ActivityLogsTable,
			Columns: []string{user.ActivityLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activitylog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActivityLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.ActivityLogsTable,
			Columns: []string{user.ActivityLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activitylog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NotificationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.NotificationsTable,
			Columns: []string{user.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNotificationsIDs(); len(nodes) > 0 && !_u.mutation.NotificationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.NotificationsTable,
			Columns: []string{user.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NotificationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.NotificationsTable,
			Columns: []string{user.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SentInvitationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.SentInvitationsTable,
			Columns: []string{user.SentInvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspaceinvitation.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSentInvitationsIDs(); len(nodes) > 0 && !_u.mutation.SentInvitationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.SentInvitationsTable,
			Columns: []string{user.SentInvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspaceinvitation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SentInvitationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.SentInvitationsTable,
			Columns: []string{user.SentInvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspaceinvitation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdateOne) SetUpdatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGoogleSub sets the "google_sub" field.
func (_u *UserUpdateOne) SetGoogleSub(v string) *UserUpdateOne {
	_u.mutation.SetGoogleSub(v)
	return _u
}

// SetNillableGoogleSub sets the "google_sub" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableGoogleSub(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetGoogleSub(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *UserUpdateOne) SetName(v string) *UserUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAvatarURL sets the "avatar_url" field.
func (_u *UserUpdateOne) SetAvatarURL(v string) *UserUpdateOne {
	_u.mutation.SetAvatarURL(v)
	return _u
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAvatarURL(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetAvatarURL(*v)
	}
	return _u
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (_u *UserUpdateOne) ClearAvatarURL() *UserUpdateOne {
	_u.mutation.ClearAvatarURL()
	return _u
}

// SetGoogleRefreshToken sets the "google_refresh_token" field.
func (_u *UserUpdateOne) SetGoogleRefreshToken(v string) *UserUpdateOne {
	_u.mutation.SetGoogleRefreshToken(v)
	return _u
}

// SetNillableGoogleRefreshToken sets the "google_refresh_token" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableGoogleRefreshToken(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetGoogleRefreshToken(*v)
	}
	return _u
}

// ClearGoogleRefreshToken clears the value of the "google_refresh_token" field.
func (_u *UserUpdateOne) ClearGoogleRefreshToken() *UserUpdateOne {
	_u.mutation.ClearGoogleRefreshToken()
	return _u
}

// SetCalendarSyncEnabled sets the "calendar_sync_enabled" field.
func (_u *UserUpdateOne) SetCalendarSyncEnabled(v bool) *UserUpdateOne {
	_u.mutation.SetCalendarSyncEnabled(v)
	return _u
}

// SetNillableCalendarSyncEnabled sets the "calendar_sync_enabled" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCalendarSyncEnabled(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetCalendarSyncEnabled(*v)
	}
	return _u
}

// SetCalendarSyncMode sets the "calendar_sync_mode" field.
func (_u *UserUpdateOne) SetCalendarSyncMode(v user.CalendarSyncMode) *UserUpdateOne {
	_u.mutation.SetCalendarSyncMode(v)
	return _u
}

// SetNillableCalendarSyncMode sets the "calendar_sync_mode" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCalendarSyncMode(v *user.CalendarSyncMode) *UserUpdateOne {
	if v != nil {
		_u.SetCalendarSyncMode(*v)
	}
	return _u
}

// ClearCalendarSyncMode clears the value of the "calendar_sync_mode" field.
func (_u *UserUpdateOne) ClearCalendarSyncMode() *UserUpdateOne {
	_u.mutation.ClearCalendarSyncMode()
	return _u
}

// AddWorkspaceMemberIDs adds the "workspace_members" edge to the WorkspaceMember entity by IDs.
func (_u *UserUpdateOne) AddWorkspaceMemberIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddWorkspaceMemberIDs(ids...)
	return _u
}

// AddWorkspaceMembers adds the "workspace_members" edges to the WorkspaceMember entity.
func (_u *UserUpdateOne) AddWorkspaceMembers(v ...*WorkspaceMember) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWorkspaceMemberIDs(ids...)
}

// AddProjectMemberIDs adds the "project_members" edge to the ProjectMember entity by IDs.
func (_u *UserUpdateOne) AddProjectMemberIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddProjectMemberIDs(ids...)
	return _u
}

// AddProjectMembers adds the "project_members" edges to the ProjectMember entity.
func (_u *UserUpdateOne) AddProjectMembers(v ...*ProjectMember) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProjectMemberIDs(ids...)
}

// AddCreatedProjectIDs adds the "created_projects" edge to the Project entity by IDs.
func (_u *UserUpdateOne) AddCreatedProjectIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddCreatedProjectIDs(ids...)
	return _u
}

// AddCreatedProjects adds the "created_projects" edges to the Project entity.
func (_u *UserUpdateOne) AddCreatedProjects(v ...*Project) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCreatedProjectIDs(ids...)
}

// AddCreatedTaskIDs adds the "created_tasks" edge to the Task entity by IDs.
func (_u *UserUpdateOne) AddCreatedTaskIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddCreatedTaskIDs(ids...)
	return _u
}

// AddCreatedTasks adds the "created_tasks" edges to the Task entity.
func (_u *UserUpdateOne) AddCreatedTasks(v ...*Task) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCreatedTaskIDs(ids...)
}

// AddTaskAssigneeIDs adds the "task_assignees" edge to the TaskAssignee entity by IDs.
func (_u *UserUpdateOne) AddTaskAssigneeIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddTaskAssigneeIDs(ids...)
	return _u
}

// AddTaskAssignees adds the "task_assignees" edges to the TaskAssignee entity.
func (_u *UserUpdateOne) AddTaskAssignees(v ...*TaskAssignee) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskAssigneeIDs(ids...)
}

// AddCalendarEventIDs adds the "calendar_events" edge to the TaskCalendarEvent entity by IDs.
func (_u *UserUpdateOne) AddCalendarEventIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddCalendarEventIDs(ids...)
	return _u
}

// AddCalendarEvents adds the "calendar_events" edges to the TaskCalendarEvent entity.
func (_u *UserUpdateOne) AddCalendarEvents(v ...*TaskCalendarEvent) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCalendarEventIDs(ids...)
}

// AddCommentIDs adds the "comments" edge to the Comment entity by IDs.
func (_u *UserUpdateOne) AddCommentIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddCommentIDs(ids...)
	return _u
}

// AddComments adds the "comments" edges to the Comment entity.
func (_u *UserUpdateOne) AddComments(v ...*Comment) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCommentIDs(ids...)
}

// AddCommentMentionIDs adds the "comment_mentions" edge to the CommentMention entity by IDs.
func (_u *UserUpdateOne) AddCommentMentionIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddCommentMentionIDs(ids...)
	return _u
}

// AddCommentMentions adds the "comment_mentions" edges to the CommentMention entity.
func (_u *UserUpdateOne) AddCommentMentions(v ...*CommentMention) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCommentMentionIDs(ids...)
}

// AddAttachmentIDs adds the "attachments" edge to the Attachment entity by IDs.
func (_u *UserUpdateOne) AddAttachmentIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the Attachment entity.
func (_u *UserUpdateOne) AddAttachments(v ...*Attachment) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// AddActivityLogIDs adds the "activity_logs" edge to the ActivityLog entity by IDs.
func (_u *UserUpdateOne) AddActivityLogIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddActivityLogIDs(ids...)
	return _u
}

// AddActivityLogs adds the "activity_logs" edges to the ActivityLog entity.
func (_u *UserUpdateOne) AddActivityLogs(v ...*ActivityLog) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddActivityLogIDs(ids...)
}

// AddNotificationIDs adds the "notifications" edge to the Notification entity by IDs.
func (_u *UserUpdateOne) AddNotificationIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddNotificationIDs(ids...)
	return _u
}

// AddNotifications adds the "notifications" edges to the Notification entity.
func (_u *UserUpdateOne) AddNotifications(v ...*Notification) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNotificationIDs(ids...)
}

// AddSentInvitationIDs adds the "sent_invitations" edge to the WorkspaceInvitation entity by IDs.
func (_u *UserUpdateOne) AddSentInvitationIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddSentInvitationIDs(ids...)
	return _u
}

// AddSentInvitations adds the "sent_invitations" edges to the WorkspaceInvitation entity.
func (_u *UserUpdateOne) AddSentInvitations(v ...*WorkspaceInvitation) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSentInvitationIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearWorkspaceMembers clears all "workspace_members" edges to the WorkspaceMember entity.
func (_u *UserUpdateOne) ClearWorkspaceMembers() *UserUpdateOne {
	_u.mutation.ClearWorkspaceMembers()
	return _u
}

// RemoveWorkspaceMemberIDs removes the "workspace_members" edge to WorkspaceMember entities by IDs.
func (_u *UserUpdateOne) RemoveWorkspaceMemberIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveWorkspaceMemberIDs(ids...)
	return _u
}

// RemoveWorkspaceMembers removes "workspace_members" edges to WorkspaceMember entities.
func (_u *UserUpdateOne) RemoveWorkspaceMembers(v ...*WorkspaceMember) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWorkspaceMemberIDs(ids...)
}

// ClearProjectMembers clears all "project_members" edges to the ProjectMember entity.
func (_u *UserUpdateOne) ClearProjectMembers() *UserUpdateOne {
	_u.mutation.ClearProjectMembers()
	return _u
}

// RemoveProjectMemberIDs removes the "project_members" edge to ProjectMember entities by IDs.
func (_u *UserUpdateOne) RemoveProjectMemberIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveProjectMemberIDs(ids...)
	return _u
}

// RemoveProjectMembers removes "project_members" edges to ProjectMember entities.
func (_u *UserUpdateOne) RemoveProjectMembers(v ...*ProjectMember) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProjectMemberIDs(ids...)
}

// ClearCreatedProjects clears all "created_projects" edges to the Project entity.
func (_u *UserUpdateOne) ClearCreatedProjects() *UserUpdateOne {
	_u.mutation.ClearCreatedProjects()
	return _u
}

// RemoveCreatedProjectIDs removes the "created_projects" edge to Project entities by IDs.
func (_u *UserUpdateOne) RemoveCreatedProjectIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveCreatedProjectIDs(ids...)
	return _u
}

// RemoveCreatedProjects removes "created_projects" edges to Project entities.
func (_u *UserUpdateOne) RemoveCreatedProjects(v ...*Project) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCreatedProjectIDs(ids...)
}

// ClearCreatedTasks clears all "created_tasks" edges to the Task entity.
func (_u *UserUpdateOne) ClearCreatedTasks() *UserUpdateOne {
	_u.mutation.ClearCreatedTasks()
	return _u
}

// RemoveCreatedTaskIDs removes the "created_tasks" edge to Task entities by IDs.
func (_u *UserUpdateOne) RemoveCreatedTaskIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveCreatedTaskIDs(ids...)
	return _u
}

// RemoveCreatedTasks removes "created_tasks" edges to Task entities.
func (_u *UserUpdateOne) RemoveCreatedTasks(v ...*Task) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCreatedTaskIDs(ids...)
}

// ClearTaskAssignees clears all "task_assignees" edges to the TaskAssignee entity.
func (_u *UserUpdateOne) ClearTaskAssignees() *UserUpdateOne {
	_u.mutation.ClearTaskAssignees()
	return _u
}

// RemoveTaskAssigneeIDs removes the "task_assignees" edge to TaskAssignee entities by IDs.
func (_u *UserUpdateOne) RemoveTaskAssigneeIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveTaskAssigneeIDs(ids...)
	return _u
}

// RemoveTaskAssignees removes "task_assignees" edges to TaskAssignee entities.
func (_u *UserUpdateOne) RemoveTaskAssignees(v ...*TaskAssignee) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskAssigneeIDs(ids...)
}

// ClearCalendarEvents clears all "calendar_events" edges to the TaskCalendarEvent entity.
func (_u *UserUpdateOne) ClearCalendarEvents() *UserUpdateOne {
	_u.mutation.ClearCalendarEvents()
	return _u
}

// RemoveCalendarEventIDs removes the "calendar_events" edge to TaskCalendarEvent entities by IDs.
func (_u *UserUpdateOne) RemoveCalendarEventIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveCalendarEventIDs(ids...)
	return _u
}

// RemoveCalendarEvents removes "calendar_events" edges to TaskCalendarEvent entities.
func (_u *UserUpdateOne) RemoveCalendarEvents(v ...*TaskCalendarEvent) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCalendarEventIDs(ids...)
}

// ClearComments clears all "comments" edges to the Comment entity.
func (_u *UserUpdateOne) ClearComments() *UserUpdateOne {
	_u.mutation.ClearComments()
	return _u
}

// RemoveCommentIDs removes the "comments" edge to Comment entities by IDs.
func (_u *UserUpdateOne) RemoveCommentIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveCommentIDs(ids...)
	return _u
}

// RemoveComments removes "comments" edges to Comment entities.
func (_u *UserUpdateOne) RemoveComments(v ...*Comment) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCommentIDs(ids...)
}

// ClearCommentMentions clears all "comment_mentions" edges to the CommentMention entity.
func (_u *UserUpdateOne) ClearCommentMentions() *UserUpdateOne {
	_u.mutation.ClearCommentMentions()
	return _u
}

// RemoveCommentMentionIDs removes the "comment_mentions" edge to CommentMention entities by IDs.
func (_u *UserUpdateOne) RemoveCommentMentionIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveCommentMentionIDs(ids...)
	return _u
}

// RemoveCommentMentions removes "comment_mentions" edges to CommentMention entities.
func (_u *UserUpdateOne) RemoveCommentMentions(v ...*CommentMention) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCommentMentionIDs(ids...)
}

// ClearAttachments clears all "attachments" edges to the Attachment entity.
func (_u *UserUpdateOne) ClearAttachments() *UserUpdateOne {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to Attachment entities by IDs.
func (_u *UserUpdateOne) RemoveAttachmentIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to Attachment entities.
func (_u *UserUpdateOne) RemoveAttachments(v ...*Attachment) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// ClearActivityLogs clears all "activity_logs" edges to the ActivityLog entity.
func (_u *UserUpdateOne) ClearActivityLogs() *UserUpdateOne {
	_u.mutation.ClearActivityLogs()
	return _u
}

// RemoveActivityLogIDs removes the "activity_logs" edge to ActivityLog entities by IDs.
func (_u *UserUpdateOne) RemoveActivityLogIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveActivityLogIDs(ids...)
	return _u
}

// RemoveActivityLogs removes "activity_logs" edges to ActivityLog entities.
func (_u *UserUpdateOne) RemoveActivityLogs(v ...*ActivityLog) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveActivityLogIDs(ids...)
}

// ClearNotifications clears all "notifications" edges to the Notification entity.
func (_u *UserUpdateOne) ClearNotifications() *UserUpdateOne {
	_u.mutation.ClearNotifications()
	return _u
}

// RemoveNotificationIDs removes the "notifications" edge to Notification entities by IDs.
func (_u *UserUpdateOne) RemoveNotificationIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveNotificationIDs(ids...)
	return _u
}

// RemoveNotifications removes "notifications" edges to Notification entities.
func (_u *UserUpdateOne) RemoveNotifications(v ...*Notification) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNotificationIDs(ids...)
}

// ClearSentInvitations clears all "sent_invitations" edges to the WorkspaceInvitation entity.
func (_u *UserUpdateOne) ClearSentInvitations() *UserUpdateOne {
	_u.mutation.ClearSentInvitations()
	return _u
}

// RemoveSentInvitationIDs removes the "sent_invitations" edge to WorkspaceInvitation entities by IDs.
func (_u *UserUpdateOne) RemoveSentInvitationIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveSentInvitationIDs(ids...)
	return _u
}

// RemoveSentInvitations removes "sent_invitations" edges to WorkspaceInvitation entities.
func (_u *UserUpdateOne) RemoveSentInvitations(v ...*WorkspaceInvitation) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSentInvitationIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.GoogleSub(); ok {
		if err := user.GoogleSubValidator(v); err != nil {
			return &ValidationError{Name: "google_sub", err: fmt.Errorf(`ent: validator failed for field "User.google_sub": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := user.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "User.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CalendarSyncMode(); ok {
		if err := user.CalendarSyncModeValidator(v); err != nil {
			return &ValidationError{Name: "calendar_sync_mode", err: fmt.Errorf(`ent: validator failed for field "User.calendar_sync_mode": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GoogleSub(); ok {
		_spec.SetField(user.FieldGoogleSub, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AvatarURL(); ok {
		_spec.SetField(user.FieldAvatarURL, field.TypeString, value)
	}
	if _u.mutation.AvatarURLCleared() {
		_spec.ClearField(user.FieldAvatarURL, field.TypeString)
	}
	if value, ok := _u.mutation.GoogleRefreshToken(); ok {
		_spec.SetField(user.FieldGoogleRefreshToken, field.TypeString, value)
	}
	if _u.mutation.GoogleRefreshTokenCleared() {
		_spec.ClearField(user.FieldGoogleRefreshToken, field.TypeString)
	}
	if value, ok := _u.mutation.CalendarSyncEnabled(); ok {
		_spec.SetField(user.FieldCalendarSyncEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CalendarSyncMode(); ok {
		_spec.SetField(user.FieldCalendarSyncMode, field.TypeEnum, value)
	}
	if _u.mutation.CalendarSyncModeCleared() {
		_spec.ClearField(user.FieldCalendarSyncMode, field.TypeEnum)
	}
	if _u.mutation.WorkspaceMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.WorkspaceMembersTable,
			Columns: []string{user.WorkspaceMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspacemember.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWorkspaceMembersIDs(); len(nodes) > 0 && !_u.mutation.WorkspaceMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.WorkspaceMembersTable,
			Columns: []string{user.WorkspaceMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspacemember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkspaceMembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.WorkspaceMembersTable,
			Columns: []string{user.WorkspaceMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspacemember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProjectMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.ProjectMembersTable,
			Columns: []string{user.ProjectMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectmember.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProjectMembersIDs(); len(nodes) > 0 && !_u.mutation.ProjectMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.ProjectMembersTable,
			Columns: []string{user.ProjectMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectmember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectMembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.ProjectMembersTable,
			Columns: []string{user.ProjectMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectmember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatedProjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CreatedProjectsTable,
			Columns: []string{user.CreatedProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCreatedProjectsIDs(); len(nodes) > 0 && !_u.mutation.CreatedProjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CreatedProjectsTable,
			Columns: []string{user.CreatedProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedProjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CreatedProjectsTable,
			Columns: []string{user.CreatedProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatedTasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CreatedTasksTable,
			Columns: []string{user.CreatedTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCreatedTasksIDs(); len(nodes) > 0 && !_u.mutation.CreatedTasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CreatedTasksTable,
			Columns: []string{user.CreatedTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedTasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CreatedTasksTable,
			Columns: []string{user.CreatedTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TaskAssigneesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.TaskAssigneesTable,
			Columns: []string{user.TaskAssigneesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignee.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTaskAssigneesIDs(); len(nodes) > 0 && !_u.mutation.TaskAssigneesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.TaskAssigneesTable,
			Columns: []string{user.TaskAssigneesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskAssigneesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.TaskAssigneesTable,
			Columns: []string{user.TaskAssigneesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CalendarEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CalendarEventsTable,
			Columns: []string{user.CalendarEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskcalendarevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCalendarEventsIDs(); len(nodes) > 0 && !_u.mutation.CalendarEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CalendarEventsTable,
			Columns: []string{user.CalendarEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskcalendarevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CalendarEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CalendarEventsTable,
			Columns: []string{user.CalendarEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskcalendarevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CommentsTable,
			Columns: []string{user.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCommentsIDs(); len(nodes) > 0 && !_u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CommentsTable,
			Columns: []string{user.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CommentsTable,
			Columns: []string{user.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CommentMentionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CommentMentionsTable,
			Columns: []string{user.CommentMentionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(commentmention.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCommentMentionsIDs(); len(nodes) > 0 && !_u.mutation.CommentMentionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CommentMentionsTable,
			Columns: []string{user.CommentMentionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(commentmention.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommentMentionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.CommentMentionsTable,
			Columns: []string{user.CommentMentionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(commentmention.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.AttachmentsTable,
			Columns: []string{user.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.AttachmentsTable,
			Columns: []string{user.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.AttachmentsTable,
			Columns: []string{user.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ActivityLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.ActivityLogsTable,
			Columns: []string{user.ActivityLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activitylog.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedActivityLogsIDs(); len(nodes) > 0 && !_u.mutation.ActivityLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.ActivityLogsTable,
			Columns: []string{user.ActivityLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activitylog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActivityLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.ActivityLogsTable,
			Columns: []string{user.ActivityLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activitylog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NotificationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.NotificationsTable,
			Columns: []string{user.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNotificationsIDs(); len(nodes) > 0 && !_u.mutation.NotificationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.NotificationsTable,
			Columns: []string{user.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NotificationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.NotificationsTable,
			Columns: []string{user.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SentInvitationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.SentInvitationsTable,
			Columns: []string{user.SentInvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspaceinvitation.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSentInvitationsIDs(); len(nodes) > 0 && !_u.mutation.SentInvitationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.SentInvitationsTable,
			Columns: []string{user.SentInvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspaceinvitation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SentInvitationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.SentInvitationsTable,
			Columns: []string{user.SentInvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspaceinvitation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
