// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/osasadev-lab/aibo_pj/server/ent/user"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// GoogleSub holds the value of the "google_sub" field.
	GoogleSub string `json:"google_sub,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// AvatarURL holds the value of the "avatar_url" field.
	AvatarURL *string `json:"avatar_url,omitempty"`
	// GoogleRefreshToken holds the value of the "google_refresh_token" field.
	GoogleRefreshToken *string `json:"-"`
	// CalendarSyncEnabled holds the value of the "calendar_sync_enabled" field.
	CalendarSyncEnabled bool `json:"calendar_sync_enabled,omitempty"`
	// CalendarSyncMode holds the value of the "calendar_sync_mode" field.
	CalendarSyncMode *user.CalendarSyncMode `json:"calendar_sync_mode,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// WorkspaceMembers holds the value of the workspace_members edge.
	WorkspaceMembers []*WorkspaceMember `json:"workspace_members,omitempty"`
	// ProjectMembers holds the value of the project_members edge.
	ProjectMembers []*ProjectMember `json:"project_members,omitempty"`
	// CreatedProjects holds the value of the created_projects edge.
	CreatedProjects []*Project `json:"created_projects,omitempty"`
	// CreatedTasks holds the value of the created_tasks edge.
	CreatedTasks []*Task `json:"created_tasks,omitempty"`
	// TaskAssignees holds the value of the task_assignees edge.
	TaskAssignees []*TaskAssignee `json:"task_assignees,omitempty"`
	// CalendarEvents holds the value of the calendar_events edge.
	CalendarEvents []*TaskCalendarEvent `json:"calendar_events,omitempty"`
	// Comments holds the value of the comments edge.
	Comments []*Comment `json:"comments,omitempty"`
	// CommentMentions holds the value of the comment_mentions edge.
	CommentMentions []*CommentMention `json:"comment_mentions,omitempty"`
	// Attachments holds the value of the attachments edge.
	Attachments []*Attachment `json:"attachments,omitempty"`
	// ActivityLogs holds the value of the activity_logs edge.
	ActivityLogs []*ActivityLog `json:"activity_logs,omitempty"`
	// Notifications holds the value of the notifications edge.
	Notifications []*Notification `json:"notifications,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [11]bool
}

// WorkspaceMembersOrErr returns the WorkspaceMembers value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) WorkspaceMembersOrErr() ([]*WorkspaceMember, error) {
	if e.loadedTypes[0] {
		return e.WorkspaceMembers, nil
	}
	return nil, &NotLoadedError{edge: "workspace_members"}
}

// ProjectMembersOrErr returns the ProjectMembers value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ProjectMembersOrErr() ([]*ProjectMember, error) {
	if e.loadedTypes[1] {
		return e.ProjectMembers, nil
	}
	return nil, &NotLoadedError{edge: "project_members"}
}

// CreatedProjectsOrErr returns the CreatedProjects value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) CreatedProjectsOrErr() ([]*Project, error) {
	if e.loadedTypes[2] {
		return e.CreatedProjects, nil
	}
	return nil, &NotLoadedError{edge: "created_projects"}
}

// CreatedTasksOrErr returns the CreatedTasks value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) CreatedTasksOrErr() ([]*Task, error) {
	if e.loadedTypes[3] {
		return e.CreatedTasks, nil
	}
	return nil, &NotLoadedError{edge: "created_tasks"}
}

// TaskAssigneesOrErr returns the TaskAssignees value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) TaskAssigneesOrErr() ([]*TaskAssignee, error) {
	if e.loadedTypes[4] {
		return e.TaskAssignees, nil
	}
	return nil, &NotLoadedError{edge: "task_assignees"}
}

// CalendarEventsOrErr returns the CalendarEvents value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) CalendarEventsOrErr() ([]*TaskCalendarEvent, error) {
	if e.loadedTypes[5] {
		return e.CalendarEvents, nil
	}
	return nil, &NotLoadedError{edge: "calendar_events"}
}

// CommentsOrErr returns the Comments value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) CommentsOrErr() ([]*Comment, error) {
	if e.loadedTypes[6] {
		return e.Comments, nil
	}
	return nil, &NotLoadedError{edge: "comments"}
}

// CommentMentionsOrErr returns the CommentMentions value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) CommentMentionsOrErr() ([]*CommentMention, error) {
	if e.loadedTypes[7] {
		return e.CommentMentions, nil
	}
	return nil, &NotLoadedError{edge: "comment_mentions"}
}

// AttachmentsOrErr returns the Attachments value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) AttachmentsOrErr() ([]*Attachment, error) {
	if e.loadedTypes[8] {
		return e.Attachments, nil
	}
	return nil, &NotLoadedError{edge: "attachments"}
}

// ActivityLogsOrErr returns the ActivityLogs value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ActivityLogsOrErr() ([]*ActivityLog, error) {
	if e.loadedTypes[9] {
		return e.ActivityLogs, nil
	}
	return nil, &NotLoadedError{edge: "activity_logs"}
}

// NotificationsOrErr returns the Notifications value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) NotificationsOrErr() ([]*Notification, error) {
	if e.loadedTypes[10] {
		return e.Notifications, nil
	}
	return nil, &NotLoadedError{edge: "notifications"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldCalendarSyncEnabled:
			values[i] = new(sql.NullBool)
		case user.FieldGoogleSub, user.FieldEmail, user.FieldName, user.FieldAvatarURL, user.FieldGoogleRefreshToken, user.FieldCalendarSyncMode:
			values[i] = new(sql.NullString)
		case user.FieldCreatedAt, user.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case user.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case user.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case user.FieldGoogleSub:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field google_sub", values[i])
			} else if value.Valid {
				_m.GoogleSub = value.String
			}
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case user.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case user.FieldAvatarURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field avatar_url", values[i])
			} else if value.Valid {
				_m.AvatarURL = new(string)
				*_m.AvatarURL = value.String
			}
		case user.FieldGoogleRefreshToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field google_refresh_token", values[i])
			} else if value.Valid {
				_m.GoogleRefreshToken = new(string)
				*_m.GoogleRefreshToken = value.String
			}
		case user.FieldCalendarSyncEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field calendar_sync_enabled", values[i])
			} else if value.Valid {
				_m.CalendarSyncEnabled = value.Bool
			}
		case user.FieldCalendarSyncMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field calendar_sync_mode", values[i])
			} else if value.Valid {
				_m.CalendarSyncMode = new(user.CalendarSyncMode)
				*_m.CalendarSyncMode = user.CalendarSyncMode(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryWorkspaceMembers queries the "workspace_members" edge of the User entity.
func (_m *User) QueryWorkspaceMembers() *WorkspaceMemberQuery {
	return NewUserClient(_m.config).QueryWorkspaceMembers(_m)
}

// QueryProjectMembers queries the "project_members" edge of the User entity.
func (_m *User) QueryProjectMembers() *ProjectMemberQuery {
	return NewUserClient(_m.config).QueryProjectMembers(_m)
}

// QueryCreatedProjects queries the "created_projects" edge of the User entity.
func (_m *User) QueryCreatedProjects() *ProjectQuery {
	return NewUserClient(_m.config).QueryCreatedProjects(_m)
}

// QueryCreatedTasks queries the "created_tasks" edge of the User entity.
func (_m *User) QueryCreatedTasks() *TaskQuery {
	return NewUserClient(_m.config).QueryCreatedTasks(_m)
}

// QueryTaskAssignees queries the "task_assignees" edge of the User entity.
func (_m *User) QueryTaskAssignees() *TaskAssigneeQuery {
	return NewUserClient(_m.config).QueryTaskAssignees(_m)
}

// QueryCalendarEvents queries the "calendar_events" edge of the User entity.
func (_m *User) QueryCalendarEvents() *TaskCalendarEventQuery {
	return NewUserClient(_m.config).QueryCalendarEvents(_m)
}

// QueryComments queries the "comments" edge of the User entity.
func (_m *User) QueryComments() *CommentQuery {
	return NewUserClient(_m.config).QueryComments(_m)
}

// QueryCommentMentions queries the "comment_mentions" edge of the User entity.
func (_m *User) QueryCommentMentions() *CommentMentionQuery {
	return NewUserClient(_m.config).QueryCommentMentions(_m)
}

// QueryAttachments queries the "attachments" edge of the User entity.
func (_m *User) QueryAttachments() *AttachmentQuery {
	return NewUserClient(_m.config).QueryAttachments(_m)
}

// QueryActivityLogs queries the "activity_logs" edge of the User entity.
func (_m *User) QueryActivityLogs() *ActivityLogQuery {
	return NewUserClient(_m.config).QueryActivityLogs(_m)
}

// QueryNotifications queries the "notifications" edge of the User entity.
func (_m *User) QueryNotifications() *NotificationQuery {
	return NewUserClient(_m.config).QueryNotifications(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("google_sub=")
	builder.WriteString(_m.GoogleSub)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.AvatarURL; v != nil {
		builder.WriteString("avatar_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("google_refresh_token=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("calendar_sync_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.CalendarSyncEnabled))
	builder.WriteString(", ")
	if v := _m.CalendarSyncMode; v != nil {
		builder.WriteString("calendar_sync_mode=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
