// Code generated by ent, DO NOT EDIT.

package workspaceinvitation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/osasadev-lab/aibo_pj/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldEQ(FieldUpdatedAt, v))
}

// WorkspaceID applies equality check predicate on the "workspace_id" field. It's identical to WorkspaceIDEQ.
func WorkspaceID(v uuid.UUID) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldEQ(FieldWorkspaceID, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldEQ(FieldEmail, v))
}

// InvitedBy applies equality check predicate on the "invited_by" field. It's identical to InvitedByEQ.
func InvitedBy(v uuid.UUID) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldEQ(FieldInvitedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldLTE(FieldUpdatedAt, v))
}

// WorkspaceIDEQ applies the EQ predicate on the "workspace_id" field.
func WorkspaceIDEQ(v uuid.UUID) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldEQ(FieldWorkspaceID, v))
}

// WorkspaceIDNEQ applies the NEQ predicate on the "workspace_id" field.
func WorkspaceIDNEQ(v uuid.UUID) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldNEQ(FieldWorkspaceID, v))
}

// WorkspaceIDIn applies the In predicate on the "workspace_id" field.
func WorkspaceIDIn(vs ...uuid.UUID) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldIn(FieldWorkspaceID, vs...))
}

// WorkspaceIDNotIn applies the NotIn predicate on the "workspace_id" field.
func WorkspaceIDNotIn(vs ...uuid.UUID) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldNotIn(FieldWorkspaceID, vs...))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldContainsFold(FieldEmail, v))
}

// InvitedByEQ applies the EQ predicate on the "invited_by" field.
func InvitedByEQ(v uuid.UUID) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldEQ(FieldInvitedBy, v))
}

// InvitedByNEQ applies the NEQ predicate on the "invited_by" field.
func InvitedByNEQ(v uuid.UUID) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldNEQ(FieldInvitedBy, v))
}

// InvitedByIn applies the In predicate on the "invited_by" field.
func InvitedByIn(vs ...uuid.UUID) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldIn(FieldInvitedBy, vs...))
}

// InvitedByNotIn applies the NotIn predicate on the "invited_by" field.
func InvitedByNotIn(vs ...uuid.UUID) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.FieldNotIn(FieldInvitedBy, vs...))
}

// HasWorkspace applies the HasEdge predicate on the "workspace" edge.
func HasWorkspace() predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, WorkspaceTable, WorkspaceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWorkspaceWith applies the HasEdge predicate on the "workspace" edge with a given conditions (other predicates).
func HasWorkspaceWith(preds ...predicate.Workspace) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(func(s *sql.Selector) {
		step := newWorkspaceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInviter applies the HasEdge predicate on the "inviter" edge.
func HasInviter() predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, InviterTable, InviterColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInviterWith applies the HasEdge predicate on the "inviter" edge with a given conditions (other predicates).
func HasInviterWith(preds ...predicate.User) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(func(s *sql.Selector) {
		step := newInviterStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WorkspaceInvitation) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WorkspaceInvitation) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WorkspaceInvitation) predicate.WorkspaceInvitation {
	return predicate.WorkspaceInvitation(sql.NotPredicates(p))
}
