// Code generated by ent, DO NOT EDIT.

package calendarwatchedmember

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/osasadev-lab/aibo_pj/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldEQ(FieldUpdatedAt, v))
}

// WorkspaceID applies equality check predicate on the "workspace_id" field. It's identical to WorkspaceIDEQ.
func WorkspaceID(v uuid.UUID) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldEQ(FieldWorkspaceID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldEQ(FieldUserID, v))
}

// WatchedUserID applies equality check predicate on the "watched_user_id" field. It's identical to WatchedUserIDEQ.
func WatchedUserID(v uuid.UUID) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldEQ(FieldWatchedUserID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldLTE(FieldUpdatedAt, v))
}

// WorkspaceIDEQ applies the EQ predicate on the "workspace_id" field.
func WorkspaceIDEQ(v uuid.UUID) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldEQ(FieldWorkspaceID, v))
}

// WorkspaceIDNEQ applies the NEQ predicate on the "workspace_id" field.
func WorkspaceIDNEQ(v uuid.UUID) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldNEQ(FieldWorkspaceID, v))
}

// WorkspaceIDIn applies the In predicate on the "workspace_id" field.
func WorkspaceIDIn(vs ...uuid.UUID) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldIn(FieldWorkspaceID, vs...))
}

// WorkspaceIDNotIn applies the NotIn predicate on the "workspace_id" field.
func WorkspaceIDNotIn(vs ...uuid.UUID) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldNotIn(FieldWorkspaceID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldNotIn(FieldUserID, vs...))
}

// WatchedUserIDEQ applies the EQ predicate on the "watched_user_id" field.
func WatchedUserIDEQ(v uuid.UUID) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldEQ(FieldWatchedUserID, v))
}

// WatchedUserIDNEQ applies the NEQ predicate on the "watched_user_id" field.
func WatchedUserIDNEQ(v uuid.UUID) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldNEQ(FieldWatchedUserID, v))
}

// WatchedUserIDIn applies the In predicate on the "watched_user_id" field.
func WatchedUserIDIn(vs ...uuid.UUID) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldIn(FieldWatchedUserID, vs...))
}

// WatchedUserIDNotIn applies the NotIn predicate on the "watched_user_id" field.
func WatchedUserIDNotIn(vs ...uuid.UUID) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.FieldNotIn(FieldWatchedUserID, vs...))
}

// HasWorkspace applies the HasEdge predicate on the "workspace" edge.
func HasWorkspace() predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, WorkspaceTable, WorkspaceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWorkspaceWith applies the HasEdge predicate on the "workspace" edge with a given conditions (other predicates).
func HasWorkspaceWith(preds ...predicate.Workspace) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(func(s *sql.Selector) {
		step := newWorkspaceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasWatchedUser applies the HasEdge predicate on the "watched_user" edge.
func HasWatchedUser() predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, WatchedUserTable, WatchedUserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWatchedUserWith applies the HasEdge predicate on the "watched_user" edge with a given conditions (other predicates).
func HasWatchedUserWith(preds ...predicate.User) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(func(s *sql.Selector) {
		step := newWatchedUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CalendarWatchedMember) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CalendarWatchedMember) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CalendarWatchedMember) predicate.CalendarWatchedMember {
	return predicate.CalendarWatchedMember(sql.NotPredicates(p))
}
