// Code generated by ent, DO NOT EDIT.

package dmattachment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/osasadev-lab/aibo_pj/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldEQ(FieldUpdatedAt, v))
}

// DmMessageID applies equality check predicate on the "dm_message_id" field. It's identical to DmMessageIDEQ.
func DmMessageID(v uuid.UUID) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldEQ(FieldDmMessageID, v))
}

// UploadedBy applies equality check predicate on the "uploaded_by" field. It's identical to UploadedByEQ.
func UploadedBy(v uuid.UUID) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldEQ(FieldUploadedBy, v))
}

// FileName applies equality check predicate on the "file_name" field. It's identical to FileNameEQ.
func FileName(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldEQ(FieldFileName, v))
}

// StorageKey applies equality check predicate on the "storage_key" field. It's identical to StorageKeyEQ.
func StorageKey(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldEQ(FieldStorageKey, v))
}

// SizeBytes applies equality check predicate on the "size_bytes" field. It's identical to SizeBytesEQ.
func SizeBytes(v int64) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldEQ(FieldSizeBytes, v))
}

// ContentType applies equality check predicate on the "content_type" field. It's identical to ContentTypeEQ.
func ContentType(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldEQ(FieldContentType, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldLTE(FieldUpdatedAt, v))
}

// DmMessageIDEQ applies the EQ predicate on the "dm_message_id" field.
func DmMessageIDEQ(v uuid.UUID) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldEQ(FieldDmMessageID, v))
}

// DmMessageIDNEQ applies the NEQ predicate on the "dm_message_id" field.
func DmMessageIDNEQ(v uuid.UUID) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldNEQ(FieldDmMessageID, v))
}

// DmMessageIDIn applies the In predicate on the "dm_message_id" field.
func DmMessageIDIn(vs ...uuid.UUID) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldIn(FieldDmMessageID, vs...))
}

// DmMessageIDNotIn applies the NotIn predicate on the "dm_message_id" field.
func DmMessageIDNotIn(vs ...uuid.UUID) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldNotIn(FieldDmMessageID, vs...))
}

// UploadedByEQ applies the EQ predicate on the "uploaded_by" field.
func UploadedByEQ(v uuid.UUID) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldEQ(FieldUploadedBy, v))
}

// UploadedByNEQ applies the NEQ predicate on the "uploaded_by" field.
func UploadedByNEQ(v uuid.UUID) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldNEQ(FieldUploadedBy, v))
}

// UploadedByIn applies the In predicate on the "uploaded_by" field.
func UploadedByIn(vs ...uuid.UUID) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldIn(FieldUploadedBy, vs...))
}

// UploadedByNotIn applies the NotIn predicate on the "uploaded_by" field.
func UploadedByNotIn(vs ...uuid.UUID) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldNotIn(FieldUploadedBy, vs...))
}

// FileNameEQ applies the EQ predicate on the "file_name" field.
func FileNameEQ(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldEQ(FieldFileName, v))
}

// FileNameNEQ applies the NEQ predicate on the "file_name" field.
func FileNameNEQ(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldNEQ(FieldFileName, v))
}

// FileNameIn applies the In predicate on the "file_name" field.
func FileNameIn(vs ...string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldIn(FieldFileName, vs...))
}

// FileNameNotIn applies the NotIn predicate on the "file_name" field.
func FileNameNotIn(vs ...string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldNotIn(FieldFileName, vs...))
}

// FileNameGT applies the GT predicate on the "file_name" field.
func FileNameGT(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldGT(FieldFileName, v))
}

// FileNameGTE applies the GTE predicate on the "file_name" field.
func FileNameGTE(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldGTE(FieldFileName, v))
}

// FileNameLT applies the LT predicate on the "file_name" field.
func FileNameLT(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldLT(FieldFileName, v))
}

// FileNameLTE applies the LTE predicate on the "file_name" field.
func FileNameLTE(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldLTE(FieldFileName, v))
}

// FileNameContains applies the Contains predicate on the "file_name" field.
func FileNameContains(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldContains(FieldFileName, v))
}

// FileNameHasPrefix applies the HasPrefix predicate on the "file_name" field.
func FileNameHasPrefix(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldHasPrefix(FieldFileName, v))
}

// FileNameHasSuffix applies the HasSuffix predicate on the "file_name" field.
func FileNameHasSuffix(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldHasSuffix(FieldFileName, v))
}

// FileNameEqualFold applies the EqualFold predicate on the "file_name" field.
func FileNameEqualFold(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldEqualFold(FieldFileName, v))
}

// FileNameContainsFold applies the ContainsFold predicate on the "file_name" field.
func FileNameContainsFold(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldContainsFold(FieldFileName, v))
}

// StorageKeyEQ applies the EQ predicate on the "storage_key" field.
func StorageKeyEQ(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldEQ(FieldStorageKey, v))
}

// StorageKeyNEQ applies the NEQ predicate on the "storage_key" field.
func StorageKeyNEQ(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldNEQ(FieldStorageKey, v))
}

// StorageKeyIn applies the In predicate on the "storage_key" field.
func StorageKeyIn(vs ...string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldIn(FieldStorageKey, vs...))
}

// StorageKeyNotIn applies the NotIn predicate on the "storage_key" field.
func StorageKeyNotIn(vs ...string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldNotIn(FieldStorageKey, vs...))
}

// StorageKeyGT applies the GT predicate on the "storage_key" field.
func StorageKeyGT(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldGT(FieldStorageKey, v))
}

// StorageKeyGTE applies the GTE predicate on the "storage_key" field.
func StorageKeyGTE(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldGTE(FieldStorageKey, v))
}

// StorageKeyLT applies the LT predicate on the "storage_key" field.
func StorageKeyLT(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldLT(FieldStorageKey, v))
}

// StorageKeyLTE applies the LTE predicate on the "storage_key" field.
func StorageKeyLTE(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldLTE(FieldStorageKey, v))
}

// StorageKeyContains applies the Contains predicate on the "storage_key" field.
func StorageKeyContains(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldContains(FieldStorageKey, v))
}

// StorageKeyHasPrefix applies the HasPrefix predicate on the "storage_key" field.
func StorageKeyHasPrefix(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldHasPrefix(FieldStorageKey, v))
}

// StorageKeyHasSuffix applies the HasSuffix predicate on the "storage_key" field.
func StorageKeyHasSuffix(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldHasSuffix(FieldStorageKey, v))
}

// StorageKeyEqualFold applies the EqualFold predicate on the "storage_key" field.
func StorageKeyEqualFold(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldEqualFold(FieldStorageKey, v))
}

// StorageKeyContainsFold applies the ContainsFold predicate on the "storage_key" field.
func StorageKeyContainsFold(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldContainsFold(FieldStorageKey, v))
}

// SizeBytesEQ applies the EQ predicate on the "size_bytes" field.
func SizeBytesEQ(v int64) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldEQ(FieldSizeBytes, v))
}

// SizeBytesNEQ applies the NEQ predicate on the "size_bytes" field.
func SizeBytesNEQ(v int64) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldNEQ(FieldSizeBytes, v))
}

// SizeBytesIn applies the In predicate on the "size_bytes" field.
func SizeBytesIn(vs ...int64) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldIn(FieldSizeBytes, vs...))
}

// SizeBytesNotIn applies the NotIn predicate on the "size_bytes" field.
func SizeBytesNotIn(vs ...int64) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldNotIn(FieldSizeBytes, vs...))
}

// SizeBytesGT applies the GT predicate on the "size_bytes" field.
func SizeBytesGT(v int64) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldGT(FieldSizeBytes, v))
}

// SizeBytesGTE applies the GTE predicate on the "size_bytes" field.
func SizeBytesGTE(v int64) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldGTE(FieldSizeBytes, v))
}

// SizeBytesLT applies the LT predicate on the "size_bytes" field.
func SizeBytesLT(v int64) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldLT(FieldSizeBytes, v))
}

// SizeBytesLTE applies the LTE predicate on the "size_bytes" field.
func SizeBytesLTE(v int64) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldLTE(FieldSizeBytes, v))
}

// ContentTypeEQ applies the EQ predicate on the "content_type" field.
func ContentTypeEQ(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldEQ(FieldContentType, v))
}

// ContentTypeNEQ applies the NEQ predicate on the "content_type" field.
func ContentTypeNEQ(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldNEQ(FieldContentType, v))
}

// ContentTypeIn applies the In predicate on the "content_type" field.
func ContentTypeIn(vs ...string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldIn(FieldContentType, vs...))
}

// ContentTypeNotIn applies the NotIn predicate on the "content_type" field.
func ContentTypeNotIn(vs ...string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldNotIn(FieldContentType, vs...))
}

// ContentTypeGT applies the GT predicate on the "content_type" field.
func ContentTypeGT(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldGT(FieldContentType, v))
}

// ContentTypeGTE applies the GTE predicate on the "content_type" field.
func ContentTypeGTE(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldGTE(FieldContentType, v))
}

// ContentTypeLT applies the LT predicate on the "content_type" field.
func ContentTypeLT(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldLT(FieldContentType, v))
}

// ContentTypeLTE applies the LTE predicate on the "content_type" field.
func ContentTypeLTE(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldLTE(FieldContentType, v))
}

// ContentTypeContains applies the Contains predicate on the "content_type" field.
func ContentTypeContains(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldContains(FieldContentType, v))
}

// ContentTypeHasPrefix applies the HasPrefix predicate on the "content_type" field.
func ContentTypeHasPrefix(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldHasPrefix(FieldContentType, v))
}

// ContentTypeHasSuffix applies the HasSuffix predicate on the "content_type" field.
func ContentTypeHasSuffix(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldHasSuffix(FieldContentType, v))
}

// ContentTypeEqualFold applies the EqualFold predicate on the "content_type" field.
func ContentTypeEqualFold(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldEqualFold(FieldContentType, v))
}

// ContentTypeContainsFold applies the ContainsFold predicate on the "content_type" field.
func ContentTypeContainsFold(v string) predicate.DMAttachment {
	return predicate.DMAttachment(sql.FieldContainsFold(FieldContentType, v))
}

// HasMessage applies the HasEdge predicate on the "message" edge.
func HasMessage() predicate.DMAttachment {
	return predicate.DMAttachment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, MessageTable, MessageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessageWith applies the HasEdge predicate on the "message" edge with a given conditions (other predicates).
func HasMessageWith(preds ...predicate.DMMessage) predicate.DMAttachment {
	return predicate.DMAttachment(func(s *sql.Selector) {
		step := newMessageStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUploader applies the HasEdge predicate on the "uploader" edge.
func HasUploader() predicate.DMAttachment {
	return predicate.DMAttachment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UploaderTable, UploaderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUploaderWith applies the HasEdge predicate on the "uploader" edge with a given conditions (other predicates).
func HasUploaderWith(preds ...predicate.User) predicate.DMAttachment {
	return predicate.DMAttachment(func(s *sql.Selector) {
		step := newUploaderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DMAttachment) predicate.DMAttachment {
	return predicate.DMAttachment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DMAttachment) predicate.DMAttachment {
	return predicate.DMAttachment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DMAttachment) predicate.DMAttachment {
	return predicate.DMAttachment(sql.NotPredicates(p))
}
